#ifndef NES_METRICCOLLECTORTYPE_HPP
#define NES_METRICCOLLECTORTYPE_HPP

namespace NES {
enum MetricCollectorType {
    CPU_COLLECTOR,
    DISK_COLLECTOR,
    MEMORY_COLLECTOR,
    NETWORK_COLLECTOR,
    STATIC_SYSTEM_METRICS_COLLECTOR,
    RUNTIME_METRICS_COLLECTOR
};

}

#endif//NES_METRICCOLLECTORTYPE_HPP
