[package]
name = "tcp_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
rand = "0.8"
csv = "1.1"
tokio-util = { version = "0.7", features = ["codec"] }