// @ts-nocheck -- generated by antlr-ng, do not edit
import { ErrorNode, ParseTreeListener, ParserRuleContext, TerminalNode } from "antlr4ng";


import { SingleStatementContext } from "./AntlrSQLParser.js";
import { TerminatedStatementContext } from "./AntlrSQLParser.js";
import { MultipleStatementsContext } from "./AntlrSQLParser.js";
import { StatementContext } from "./AntlrSQLParser.js";
import { ExplainStatementContext } from "./AntlrSQLParser.js";
import { CreateStatementContext } from "./AntlrSQLParser.js";
import { CreateDefinitionContext } from "./AntlrSQLParser.js";
import { CreateLogicalSourceDefinitionContext } from "./AntlrSQLParser.js";
import { CreatePhysicalSourceDefinitionContext } from "./AntlrSQLParser.js";
import { OptionsClauseContext } from "./AntlrSQLParser.js";
import { CreateSinkDefinitionContext } from "./AntlrSQLParser.js";
import { SchemaDefinitionContext } from "./AntlrSQLParser.js";
import { ColumnDefinitionContext } from "./AntlrSQLParser.js";
import { TypeDefinitionContext } from "./AntlrSQLParser.js";
import { NullableDefinitionContext } from "./AntlrSQLParser.js";
import { FromQueryContext } from "./AntlrSQLParser.js";
import { DropStatementContext } from "./AntlrSQLParser.js";
import { DropSubjectContext } from "./AntlrSQLParser.js";
import { DropQueryContext } from "./AntlrSQLParser.js";
import { DropSourceContext } from "./AntlrSQLParser.js";
import { DropLogicalSourceSubjectContext } from "./AntlrSQLParser.js";
import { DropPhysicalSourceSubjectContext } from "./AntlrSQLParser.js";
import { DropSinkContext } from "./AntlrSQLParser.js";
import { DropFilterContext } from "./AntlrSQLParser.js";
import { ShowStatementContext } from "./AntlrSQLParser.js";
import { ShowFormatContext } from "./AntlrSQLParser.js";
import { ShowQueriesSubjectContext } from "./AntlrSQLParser.js";
import { ShowLogicalSourcesSubjectContext } from "./AntlrSQLParser.js";
import { ShowPhysicalSourcesSubjectContext } from "./AntlrSQLParser.js";
import { ShowSinksSubjectContext } from "./AntlrSQLParser.js";
import { ShowFilterContext } from "./AntlrSQLParser.js";
import { QueryWithOptionsContext } from "./AntlrSQLParser.js";
import { QueryContext } from "./AntlrSQLParser.js";
import { QueryOrganizationContext } from "./AntlrSQLParser.js";
import { PrimaryQueryContext } from "./AntlrSQLParser.js";
import { SetOperationContext } from "./AntlrSQLParser.js";
import { QueryPrimaryDefaultContext } from "./AntlrSQLParser.js";
import { FromStmtContext } from "./AntlrSQLParser.js";
import { TableContext } from "./AntlrSQLParser.js";
import { InlineTableDefault1Context } from "./AntlrSQLParser.js";
import { SubqueryContext } from "./AntlrSQLParser.js";
import { QuerySpecificationContext } from "./AntlrSQLParser.js";
import { FromClauseContext } from "./AntlrSQLParser.js";
import { RelationContext } from "./AntlrSQLParser.js";
import { JoinRelationContext } from "./AntlrSQLParser.js";
import { JoinTypeContext } from "./AntlrSQLParser.js";
import { JoinCriteriaContext } from "./AntlrSQLParser.js";
import { TableNameContext } from "./AntlrSQLParser.js";
import { AliasedQueryContext } from "./AntlrSQLParser.js";
import { AliasedRelationContext } from "./AntlrSQLParser.js";
import { InlineTableDefault2Context } from "./AntlrSQLParser.js";
import { InlineDefinedSourceContext } from "./AntlrSQLParser.js";
import { InlineSourceContext } from "./AntlrSQLParser.js";
import { SchemaContext } from "./AntlrSQLParser.js";
import { FromStatementContext } from "./AntlrSQLParser.js";
import { FromStatementBodyContext } from "./AntlrSQLParser.js";
import { SelectClauseContext } from "./AntlrSQLParser.js";
import { WhereClauseContext } from "./AntlrSQLParser.js";
import { HavingClauseContext } from "./AntlrSQLParser.js";
import { InlineTableContext } from "./AntlrSQLParser.js";
import { TableAliasContext } from "./AntlrSQLParser.js";
import { MultipartIdentifierContext } from "./AntlrSQLParser.js";
import { NamedConfigExpressionContext } from "./AntlrSQLParser.js";
import { NamedExpressionContext } from "./AntlrSQLParser.js";
import { IdentifierContext } from "./AntlrSQLParser.js";
import { UnquotedIdentifierContext } from "./AntlrSQLParser.js";
import { QuotedIdentifierAlternativeContext } from "./AntlrSQLParser.js";
import { QuotedIdentifierContext } from "./AntlrSQLParser.js";
import { IdentifierChainContext } from "./AntlrSQLParser.js";
import { IdentifierListContext } from "./AntlrSQLParser.js";
import { IdentifierSeqContext } from "./AntlrSQLParser.js";
import { ErrorCapturingIdentifierContext } from "./AntlrSQLParser.js";
import { ErrorIdentContext } from "./AntlrSQLParser.js";
import { RealIdentContext } from "./AntlrSQLParser.js";
import { NamedConfigExpressionSeqContext } from "./AntlrSQLParser.js";
import { NamedExpressionSeqContext } from "./AntlrSQLParser.js";
import { ExpressionContext } from "./AntlrSQLParser.js";
import { LogicalNotContext } from "./AntlrSQLParser.js";
import { ExistsContext } from "./AntlrSQLParser.js";
import { PredicatedContext } from "./AntlrSQLParser.js";
import { LogicalBinaryContext } from "./AntlrSQLParser.js";
import { WindowedAggregationClauseContext } from "./AntlrSQLParser.js";
import { GroupByClauseContext } from "./AntlrSQLParser.js";
import { GroupingSetContext } from "./AntlrSQLParser.js";
import { WindowClauseContext } from "./AntlrSQLParser.js";
import { WatermarkClauseContext } from "./AntlrSQLParser.js";
import { WatermarkParametersContext } from "./AntlrSQLParser.js";
import { TimeBasedWindowContext } from "./AntlrSQLParser.js";
import { CountBasedWindowContext } from "./AntlrSQLParser.js";
import { ThresholdBasedWindowContext } from "./AntlrSQLParser.js";
import { TumblingWindowContext } from "./AntlrSQLParser.js";
import { SlidingWindowContext } from "./AntlrSQLParser.js";
import { CountBasedTumblingContext } from "./AntlrSQLParser.js";
import { ThresholdWindowContext } from "./AntlrSQLParser.js";
import { ConditionParameterContext } from "./AntlrSQLParser.js";
import { ThresholdMinSizeParameterContext } from "./AntlrSQLParser.js";
import { SizeParameterContext } from "./AntlrSQLParser.js";
import { AdvancebyParameterContext } from "./AntlrSQLParser.js";
import { TimeUnitContext } from "./AntlrSQLParser.js";
import { TimestampParameterContext } from "./AntlrSQLParser.js";
import { FunctionNameContext } from "./AntlrSQLParser.js";
import { SinkClauseContext } from "./AntlrSQLParser.js";
import { SinkContext } from "./AntlrSQLParser.js";
import { InlineSinkContext } from "./AntlrSQLParser.js";
import { NullNotnullContext } from "./AntlrSQLParser.js";
import { StreamNameContext } from "./AntlrSQLParser.js";
import { FileFormatContext } from "./AntlrSQLParser.js";
import { SortItemContext } from "./AntlrSQLParser.js";
import { PredicateContext } from "./AntlrSQLParser.js";
import { FunctionCallContext } from "./AntlrSQLParser.js";
import { ArithmeticUnaryContext } from "./AntlrSQLParser.js";
import { ValueExpressionDefaultContext } from "./AntlrSQLParser.js";
import { ArithmeticBinaryContext } from "./AntlrSQLParser.js";
import { ComparisonContext } from "./AntlrSQLParser.js";
import { ComparisonOperatorContext } from "./AntlrSQLParser.js";
import { HintContext } from "./AntlrSQLParser.js";
import { HintStatementContext } from "./AntlrSQLParser.js";
import { StarContext } from "./AntlrSQLParser.js";
import { SubqueryExpressionContext } from "./AntlrSQLParser.js";
import { RowConstructorContext } from "./AntlrSQLParser.js";
import { ParenthesizedExpressionContext } from "./AntlrSQLParser.js";
import { ConstantDefaultContext } from "./AntlrSQLParser.js";
import { ColumnReferenceContext } from "./AntlrSQLParser.js";
import { DereferenceContext } from "./AntlrSQLParser.js";
import { QualifiedNameContext } from "./AntlrSQLParser.js";
import { IntegerLiteralContext } from "./AntlrSQLParser.js";
import { FloatLiteralContext } from "./AntlrSQLParser.js";
import { UnsignedIntegerLiteralContext } from "./AntlrSQLParser.js";
import { SignedIntegerLiteralContext } from "./AntlrSQLParser.js";
import { NullLiteralContext } from "./AntlrSQLParser.js";
import { TypeConstructorContext } from "./AntlrSQLParser.js";
import { NumericLiteralContext } from "./AntlrSQLParser.js";
import { BooleanLiteralContext } from "./AntlrSQLParser.js";
import { StringLiteralContext } from "./AntlrSQLParser.js";
import { BooleanValueContext } from "./AntlrSQLParser.js";


/**
 * This interface defines a complete listener for a parse tree produced by
 * `AntlrSQLParser`.
 */
export class AntlrSQLListener implements ParseTreeListener {
    /**
     * Enter a parse tree produced by `AntlrSQLParser.singleStatement`.
     * @param ctx the parse tree
     */
    enterSingleStatement?: (ctx: SingleStatementContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.singleStatement`.
     * @param ctx the parse tree
     */
    exitSingleStatement?: (ctx: SingleStatementContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.terminatedStatement`.
     * @param ctx the parse tree
     */
    enterTerminatedStatement?: (ctx: TerminatedStatementContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.terminatedStatement`.
     * @param ctx the parse tree
     */
    exitTerminatedStatement?: (ctx: TerminatedStatementContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.multipleStatements`.
     * @param ctx the parse tree
     */
    enterMultipleStatements?: (ctx: MultipleStatementsContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.multipleStatements`.
     * @param ctx the parse tree
     */
    exitMultipleStatements?: (ctx: MultipleStatementsContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.statement`.
     * @param ctx the parse tree
     */
    enterStatement?: (ctx: StatementContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.statement`.
     * @param ctx the parse tree
     */
    exitStatement?: (ctx: StatementContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.explainStatement`.
     * @param ctx the parse tree
     */
    enterExplainStatement?: (ctx: ExplainStatementContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.explainStatement`.
     * @param ctx the parse tree
     */
    exitExplainStatement?: (ctx: ExplainStatementContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.createStatement`.
     * @param ctx the parse tree
     */
    enterCreateStatement?: (ctx: CreateStatementContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.createStatement`.
     * @param ctx the parse tree
     */
    exitCreateStatement?: (ctx: CreateStatementContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.createDefinition`.
     * @param ctx the parse tree
     */
    enterCreateDefinition?: (ctx: CreateDefinitionContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.createDefinition`.
     * @param ctx the parse tree
     */
    exitCreateDefinition?: (ctx: CreateDefinitionContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.createLogicalSourceDefinition`.
     * @param ctx the parse tree
     */
    enterCreateLogicalSourceDefinition?: (ctx: CreateLogicalSourceDefinitionContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.createLogicalSourceDefinition`.
     * @param ctx the parse tree
     */
    exitCreateLogicalSourceDefinition?: (ctx: CreateLogicalSourceDefinitionContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.createPhysicalSourceDefinition`.
     * @param ctx the parse tree
     */
    enterCreatePhysicalSourceDefinition?: (ctx: CreatePhysicalSourceDefinitionContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.createPhysicalSourceDefinition`.
     * @param ctx the parse tree
     */
    exitCreatePhysicalSourceDefinition?: (ctx: CreatePhysicalSourceDefinitionContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.optionsClause`.
     * @param ctx the parse tree
     */
    enterOptionsClause?: (ctx: OptionsClauseContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.optionsClause`.
     * @param ctx the parse tree
     */
    exitOptionsClause?: (ctx: OptionsClauseContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.createSinkDefinition`.
     * @param ctx the parse tree
     */
    enterCreateSinkDefinition?: (ctx: CreateSinkDefinitionContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.createSinkDefinition`.
     * @param ctx the parse tree
     */
    exitCreateSinkDefinition?: (ctx: CreateSinkDefinitionContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.schemaDefinition`.
     * @param ctx the parse tree
     */
    enterSchemaDefinition?: (ctx: SchemaDefinitionContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.schemaDefinition`.
     * @param ctx the parse tree
     */
    exitSchemaDefinition?: (ctx: SchemaDefinitionContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.columnDefinition`.
     * @param ctx the parse tree
     */
    enterColumnDefinition?: (ctx: ColumnDefinitionContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.columnDefinition`.
     * @param ctx the parse tree
     */
    exitColumnDefinition?: (ctx: ColumnDefinitionContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.typeDefinition`.
     * @param ctx the parse tree
     */
    enterTypeDefinition?: (ctx: TypeDefinitionContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.typeDefinition`.
     * @param ctx the parse tree
     */
    exitTypeDefinition?: (ctx: TypeDefinitionContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.nullableDefinition`.
     * @param ctx the parse tree
     */
    enterNullableDefinition?: (ctx: NullableDefinitionContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.nullableDefinition`.
     * @param ctx the parse tree
     */
    exitNullableDefinition?: (ctx: NullableDefinitionContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.fromQuery`.
     * @param ctx the parse tree
     */
    enterFromQuery?: (ctx: FromQueryContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.fromQuery`.
     * @param ctx the parse tree
     */
    exitFromQuery?: (ctx: FromQueryContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.dropStatement`.
     * @param ctx the parse tree
     */
    enterDropStatement?: (ctx: DropStatementContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.dropStatement`.
     * @param ctx the parse tree
     */
    exitDropStatement?: (ctx: DropStatementContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.dropSubject`.
     * @param ctx the parse tree
     */
    enterDropSubject?: (ctx: DropSubjectContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.dropSubject`.
     * @param ctx the parse tree
     */
    exitDropSubject?: (ctx: DropSubjectContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.dropQuery`.
     * @param ctx the parse tree
     */
    enterDropQuery?: (ctx: DropQueryContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.dropQuery`.
     * @param ctx the parse tree
     */
    exitDropQuery?: (ctx: DropQueryContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.dropSource`.
     * @param ctx the parse tree
     */
    enterDropSource?: (ctx: DropSourceContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.dropSource`.
     * @param ctx the parse tree
     */
    exitDropSource?: (ctx: DropSourceContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.dropLogicalSourceSubject`.
     * @param ctx the parse tree
     */
    enterDropLogicalSourceSubject?: (ctx: DropLogicalSourceSubjectContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.dropLogicalSourceSubject`.
     * @param ctx the parse tree
     */
    exitDropLogicalSourceSubject?: (ctx: DropLogicalSourceSubjectContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.dropPhysicalSourceSubject`.
     * @param ctx the parse tree
     */
    enterDropPhysicalSourceSubject?: (ctx: DropPhysicalSourceSubjectContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.dropPhysicalSourceSubject`.
     * @param ctx the parse tree
     */
    exitDropPhysicalSourceSubject?: (ctx: DropPhysicalSourceSubjectContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.dropSink`.
     * @param ctx the parse tree
     */
    enterDropSink?: (ctx: DropSinkContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.dropSink`.
     * @param ctx the parse tree
     */
    exitDropSink?: (ctx: DropSinkContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.dropFilter`.
     * @param ctx the parse tree
     */
    enterDropFilter?: (ctx: DropFilterContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.dropFilter`.
     * @param ctx the parse tree
     */
    exitDropFilter?: (ctx: DropFilterContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.showStatement`.
     * @param ctx the parse tree
     */
    enterShowStatement?: (ctx: ShowStatementContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.showStatement`.
     * @param ctx the parse tree
     */
    exitShowStatement?: (ctx: ShowStatementContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.showFormat`.
     * @param ctx the parse tree
     */
    enterShowFormat?: (ctx: ShowFormatContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.showFormat`.
     * @param ctx the parse tree
     */
    exitShowFormat?: (ctx: ShowFormatContext) => void;
    /**
     * Enter a parse tree produced by the `showQueriesSubject`
     * labeled alternative in `AntlrSQLParser.showSubject`.
     * @param ctx the parse tree
     */
    enterShowQueriesSubject?: (ctx: ShowQueriesSubjectContext) => void;
    /**
     * Exit a parse tree produced by the `showQueriesSubject`
     * labeled alternative in `AntlrSQLParser.showSubject`.
     * @param ctx the parse tree
     */
    exitShowQueriesSubject?: (ctx: ShowQueriesSubjectContext) => void;
    /**
     * Enter a parse tree produced by the `showLogicalSourcesSubject`
     * labeled alternative in `AntlrSQLParser.showSubject`.
     * @param ctx the parse tree
     */
    enterShowLogicalSourcesSubject?: (ctx: ShowLogicalSourcesSubjectContext) => void;
    /**
     * Exit a parse tree produced by the `showLogicalSourcesSubject`
     * labeled alternative in `AntlrSQLParser.showSubject`.
     * @param ctx the parse tree
     */
    exitShowLogicalSourcesSubject?: (ctx: ShowLogicalSourcesSubjectContext) => void;
    /**
     * Enter a parse tree produced by the `showPhysicalSourcesSubject`
     * labeled alternative in `AntlrSQLParser.showSubject`.
     * @param ctx the parse tree
     */
    enterShowPhysicalSourcesSubject?: (ctx: ShowPhysicalSourcesSubjectContext) => void;
    /**
     * Exit a parse tree produced by the `showPhysicalSourcesSubject`
     * labeled alternative in `AntlrSQLParser.showSubject`.
     * @param ctx the parse tree
     */
    exitShowPhysicalSourcesSubject?: (ctx: ShowPhysicalSourcesSubjectContext) => void;
    /**
     * Enter a parse tree produced by the `showSinksSubject`
     * labeled alternative in `AntlrSQLParser.showSubject`.
     * @param ctx the parse tree
     */
    enterShowSinksSubject?: (ctx: ShowSinksSubjectContext) => void;
    /**
     * Exit a parse tree produced by the `showSinksSubject`
     * labeled alternative in `AntlrSQLParser.showSubject`.
     * @param ctx the parse tree
     */
    exitShowSinksSubject?: (ctx: ShowSinksSubjectContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.showFilter`.
     * @param ctx the parse tree
     */
    enterShowFilter?: (ctx: ShowFilterContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.showFilter`.
     * @param ctx the parse tree
     */
    exitShowFilter?: (ctx: ShowFilterContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.queryWithOptions`.
     * @param ctx the parse tree
     */
    enterQueryWithOptions?: (ctx: QueryWithOptionsContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.queryWithOptions`.
     * @param ctx the parse tree
     */
    exitQueryWithOptions?: (ctx: QueryWithOptionsContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.query`.
     * @param ctx the parse tree
     */
    enterQuery?: (ctx: QueryContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.query`.
     * @param ctx the parse tree
     */
    exitQuery?: (ctx: QueryContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.queryOrganization`.
     * @param ctx the parse tree
     */
    enterQueryOrganization?: (ctx: QueryOrganizationContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.queryOrganization`.
     * @param ctx the parse tree
     */
    exitQueryOrganization?: (ctx: QueryOrganizationContext) => void;
    /**
     * Enter a parse tree produced by the `primaryQuery`
     * labeled alternative in `AntlrSQLParser.queryTerm`.
     * @param ctx the parse tree
     */
    enterPrimaryQuery?: (ctx: PrimaryQueryContext) => void;
    /**
     * Exit a parse tree produced by the `primaryQuery`
     * labeled alternative in `AntlrSQLParser.queryTerm`.
     * @param ctx the parse tree
     */
    exitPrimaryQuery?: (ctx: PrimaryQueryContext) => void;
    /**
     * Enter a parse tree produced by the `setOperation`
     * labeled alternative in `AntlrSQLParser.queryTerm`.
     * @param ctx the parse tree
     */
    enterSetOperation?: (ctx: SetOperationContext) => void;
    /**
     * Exit a parse tree produced by the `setOperation`
     * labeled alternative in `AntlrSQLParser.queryTerm`.
     * @param ctx the parse tree
     */
    exitSetOperation?: (ctx: SetOperationContext) => void;
    /**
     * Enter a parse tree produced by the `queryPrimaryDefault`
     * labeled alternative in `AntlrSQLParser.queryPrimary`.
     * @param ctx the parse tree
     */
    enterQueryPrimaryDefault?: (ctx: QueryPrimaryDefaultContext) => void;
    /**
     * Exit a parse tree produced by the `queryPrimaryDefault`
     * labeled alternative in `AntlrSQLParser.queryPrimary`.
     * @param ctx the parse tree
     */
    exitQueryPrimaryDefault?: (ctx: QueryPrimaryDefaultContext) => void;
    /**
     * Enter a parse tree produced by the `fromStmt`
     * labeled alternative in `AntlrSQLParser.queryPrimary`.
     * @param ctx the parse tree
     */
    enterFromStmt?: (ctx: FromStmtContext) => void;
    /**
     * Exit a parse tree produced by the `fromStmt`
     * labeled alternative in `AntlrSQLParser.queryPrimary`.
     * @param ctx the parse tree
     */
    exitFromStmt?: (ctx: FromStmtContext) => void;
    /**
     * Enter a parse tree produced by the `table`
     * labeled alternative in `AntlrSQLParser.queryPrimary`.
     * @param ctx the parse tree
     */
    enterTable?: (ctx: TableContext) => void;
    /**
     * Exit a parse tree produced by the `table`
     * labeled alternative in `AntlrSQLParser.queryPrimary`.
     * @param ctx the parse tree
     */
    exitTable?: (ctx: TableContext) => void;
    /**
     * Enter a parse tree produced by the `inlineTableDefault1`
     * labeled alternative in `AntlrSQLParser.queryPrimary`.
     * @param ctx the parse tree
     */
    enterInlineTableDefault1?: (ctx: InlineTableDefault1Context) => void;
    /**
     * Exit a parse tree produced by the `inlineTableDefault1`
     * labeled alternative in `AntlrSQLParser.queryPrimary`.
     * @param ctx the parse tree
     */
    exitInlineTableDefault1?: (ctx: InlineTableDefault1Context) => void;
    /**
     * Enter a parse tree produced by the `subquery`
     * labeled alternative in `AntlrSQLParser.queryPrimary`.
     * @param ctx the parse tree
     */
    enterSubquery?: (ctx: SubqueryContext) => void;
    /**
     * Exit a parse tree produced by the `subquery`
     * labeled alternative in `AntlrSQLParser.queryPrimary`.
     * @param ctx the parse tree
     */
    exitSubquery?: (ctx: SubqueryContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.querySpecification`.
     * @param ctx the parse tree
     */
    enterQuerySpecification?: (ctx: QuerySpecificationContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.querySpecification`.
     * @param ctx the parse tree
     */
    exitQuerySpecification?: (ctx: QuerySpecificationContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.fromClause`.
     * @param ctx the parse tree
     */
    enterFromClause?: (ctx: FromClauseContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.fromClause`.
     * @param ctx the parse tree
     */
    exitFromClause?: (ctx: FromClauseContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.relation`.
     * @param ctx the parse tree
     */
    enterRelation?: (ctx: RelationContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.relation`.
     * @param ctx the parse tree
     */
    exitRelation?: (ctx: RelationContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.joinRelation`.
     * @param ctx the parse tree
     */
    enterJoinRelation?: (ctx: JoinRelationContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.joinRelation`.
     * @param ctx the parse tree
     */
    exitJoinRelation?: (ctx: JoinRelationContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.joinType`.
     * @param ctx the parse tree
     */
    enterJoinType?: (ctx: JoinTypeContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.joinType`.
     * @param ctx the parse tree
     */
    exitJoinType?: (ctx: JoinTypeContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.joinCriteria`.
     * @param ctx the parse tree
     */
    enterJoinCriteria?: (ctx: JoinCriteriaContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.joinCriteria`.
     * @param ctx the parse tree
     */
    exitJoinCriteria?: (ctx: JoinCriteriaContext) => void;
    /**
     * Enter a parse tree produced by the `tableName`
     * labeled alternative in `AntlrSQLParser.relationPrimary`.
     * @param ctx the parse tree
     */
    enterTableName?: (ctx: TableNameContext) => void;
    /**
     * Exit a parse tree produced by the `tableName`
     * labeled alternative in `AntlrSQLParser.relationPrimary`.
     * @param ctx the parse tree
     */
    exitTableName?: (ctx: TableNameContext) => void;
    /**
     * Enter a parse tree produced by the `aliasedQuery`
     * labeled alternative in `AntlrSQLParser.relationPrimary`.
     * @param ctx the parse tree
     */
    enterAliasedQuery?: (ctx: AliasedQueryContext) => void;
    /**
     * Exit a parse tree produced by the `aliasedQuery`
     * labeled alternative in `AntlrSQLParser.relationPrimary`.
     * @param ctx the parse tree
     */
    exitAliasedQuery?: (ctx: AliasedQueryContext) => void;
    /**
     * Enter a parse tree produced by the `aliasedRelation`
     * labeled alternative in `AntlrSQLParser.relationPrimary`.
     * @param ctx the parse tree
     */
    enterAliasedRelation?: (ctx: AliasedRelationContext) => void;
    /**
     * Exit a parse tree produced by the `aliasedRelation`
     * labeled alternative in `AntlrSQLParser.relationPrimary`.
     * @param ctx the parse tree
     */
    exitAliasedRelation?: (ctx: AliasedRelationContext) => void;
    /**
     * Enter a parse tree produced by the `inlineTableDefault2`
     * labeled alternative in `AntlrSQLParser.relationPrimary`.
     * @param ctx the parse tree
     */
    enterInlineTableDefault2?: (ctx: InlineTableDefault2Context) => void;
    /**
     * Exit a parse tree produced by the `inlineTableDefault2`
     * labeled alternative in `AntlrSQLParser.relationPrimary`.
     * @param ctx the parse tree
     */
    exitInlineTableDefault2?: (ctx: InlineTableDefault2Context) => void;
    /**
     * Enter a parse tree produced by the `inlineDefinedSource`
     * labeled alternative in `AntlrSQLParser.relationPrimary`.
     * @param ctx the parse tree
     */
    enterInlineDefinedSource?: (ctx: InlineDefinedSourceContext) => void;
    /**
     * Exit a parse tree produced by the `inlineDefinedSource`
     * labeled alternative in `AntlrSQLParser.relationPrimary`.
     * @param ctx the parse tree
     */
    exitInlineDefinedSource?: (ctx: InlineDefinedSourceContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.inlineSource`.
     * @param ctx the parse tree
     */
    enterInlineSource?: (ctx: InlineSourceContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.inlineSource`.
     * @param ctx the parse tree
     */
    exitInlineSource?: (ctx: InlineSourceContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.schema`.
     * @param ctx the parse tree
     */
    enterSchema?: (ctx: SchemaContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.schema`.
     * @param ctx the parse tree
     */
    exitSchema?: (ctx: SchemaContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.fromStatement`.
     * @param ctx the parse tree
     */
    enterFromStatement?: (ctx: FromStatementContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.fromStatement`.
     * @param ctx the parse tree
     */
    exitFromStatement?: (ctx: FromStatementContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.fromStatementBody`.
     * @param ctx the parse tree
     */
    enterFromStatementBody?: (ctx: FromStatementBodyContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.fromStatementBody`.
     * @param ctx the parse tree
     */
    exitFromStatementBody?: (ctx: FromStatementBodyContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.selectClause`.
     * @param ctx the parse tree
     */
    enterSelectClause?: (ctx: SelectClauseContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.selectClause`.
     * @param ctx the parse tree
     */
    exitSelectClause?: (ctx: SelectClauseContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.whereClause`.
     * @param ctx the parse tree
     */
    enterWhereClause?: (ctx: WhereClauseContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.whereClause`.
     * @param ctx the parse tree
     */
    exitWhereClause?: (ctx: WhereClauseContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.havingClause`.
     * @param ctx the parse tree
     */
    enterHavingClause?: (ctx: HavingClauseContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.havingClause`.
     * @param ctx the parse tree
     */
    exitHavingClause?: (ctx: HavingClauseContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.inlineTable`.
     * @param ctx the parse tree
     */
    enterInlineTable?: (ctx: InlineTableContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.inlineTable`.
     * @param ctx the parse tree
     */
    exitInlineTable?: (ctx: InlineTableContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.tableAlias`.
     * @param ctx the parse tree
     */
    enterTableAlias?: (ctx: TableAliasContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.tableAlias`.
     * @param ctx the parse tree
     */
    exitTableAlias?: (ctx: TableAliasContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.multipartIdentifier`.
     * @param ctx the parse tree
     */
    enterMultipartIdentifier?: (ctx: MultipartIdentifierContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.multipartIdentifier`.
     * @param ctx the parse tree
     */
    exitMultipartIdentifier?: (ctx: MultipartIdentifierContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.namedConfigExpression`.
     * @param ctx the parse tree
     */
    enterNamedConfigExpression?: (ctx: NamedConfigExpressionContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.namedConfigExpression`.
     * @param ctx the parse tree
     */
    exitNamedConfigExpression?: (ctx: NamedConfigExpressionContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.namedExpression`.
     * @param ctx the parse tree
     */
    enterNamedExpression?: (ctx: NamedExpressionContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.namedExpression`.
     * @param ctx the parse tree
     */
    exitNamedExpression?: (ctx: NamedExpressionContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.identifier`.
     * @param ctx the parse tree
     */
    enterIdentifier?: (ctx: IdentifierContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.identifier`.
     * @param ctx the parse tree
     */
    exitIdentifier?: (ctx: IdentifierContext) => void;
    /**
     * Enter a parse tree produced by the `unquotedIdentifier`
     * labeled alternative in `AntlrSQLParser.strictIdentifier`.
     * @param ctx the parse tree
     */
    enterUnquotedIdentifier?: (ctx: UnquotedIdentifierContext) => void;
    /**
     * Exit a parse tree produced by the `unquotedIdentifier`
     * labeled alternative in `AntlrSQLParser.strictIdentifier`.
     * @param ctx the parse tree
     */
    exitUnquotedIdentifier?: (ctx: UnquotedIdentifierContext) => void;
    /**
     * Enter a parse tree produced by the `quotedIdentifierAlternative`
     * labeled alternative in `AntlrSQLParser.strictIdentifier`.
     * @param ctx the parse tree
     */
    enterQuotedIdentifierAlternative?: (ctx: QuotedIdentifierAlternativeContext) => void;
    /**
     * Exit a parse tree produced by the `quotedIdentifierAlternative`
     * labeled alternative in `AntlrSQLParser.strictIdentifier`.
     * @param ctx the parse tree
     */
    exitQuotedIdentifierAlternative?: (ctx: QuotedIdentifierAlternativeContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.quotedIdentifier`.
     * @param ctx the parse tree
     */
    enterQuotedIdentifier?: (ctx: QuotedIdentifierContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.quotedIdentifier`.
     * @param ctx the parse tree
     */
    exitQuotedIdentifier?: (ctx: QuotedIdentifierContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.identifierChain`.
     * @param ctx the parse tree
     */
    enterIdentifierChain?: (ctx: IdentifierChainContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.identifierChain`.
     * @param ctx the parse tree
     */
    exitIdentifierChain?: (ctx: IdentifierChainContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.identifierList`.
     * @param ctx the parse tree
     */
    enterIdentifierList?: (ctx: IdentifierListContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.identifierList`.
     * @param ctx the parse tree
     */
    exitIdentifierList?: (ctx: IdentifierListContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.identifierSeq`.
     * @param ctx the parse tree
     */
    enterIdentifierSeq?: (ctx: IdentifierSeqContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.identifierSeq`.
     * @param ctx the parse tree
     */
    exitIdentifierSeq?: (ctx: IdentifierSeqContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.errorCapturingIdentifier`.
     * @param ctx the parse tree
     */
    enterErrorCapturingIdentifier?: (ctx: ErrorCapturingIdentifierContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.errorCapturingIdentifier`.
     * @param ctx the parse tree
     */
    exitErrorCapturingIdentifier?: (ctx: ErrorCapturingIdentifierContext) => void;
    /**
     * Enter a parse tree produced by the `errorIdent`
     * labeled alternative in `AntlrSQLParser.errorCapturingIdentifierExtra`.
     * @param ctx the parse tree
     */
    enterErrorIdent?: (ctx: ErrorIdentContext) => void;
    /**
     * Exit a parse tree produced by the `errorIdent`
     * labeled alternative in `AntlrSQLParser.errorCapturingIdentifierExtra`.
     * @param ctx the parse tree
     */
    exitErrorIdent?: (ctx: ErrorIdentContext) => void;
    /**
     * Enter a parse tree produced by the `realIdent`
     * labeled alternative in `AntlrSQLParser.errorCapturingIdentifierExtra`.
     * @param ctx the parse tree
     */
    enterRealIdent?: (ctx: RealIdentContext) => void;
    /**
     * Exit a parse tree produced by the `realIdent`
     * labeled alternative in `AntlrSQLParser.errorCapturingIdentifierExtra`.
     * @param ctx the parse tree
     */
    exitRealIdent?: (ctx: RealIdentContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.namedConfigExpressionSeq`.
     * @param ctx the parse tree
     */
    enterNamedConfigExpressionSeq?: (ctx: NamedConfigExpressionSeqContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.namedConfigExpressionSeq`.
     * @param ctx the parse tree
     */
    exitNamedConfigExpressionSeq?: (ctx: NamedConfigExpressionSeqContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.namedExpressionSeq`.
     * @param ctx the parse tree
     */
    enterNamedExpressionSeq?: (ctx: NamedExpressionSeqContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.namedExpressionSeq`.
     * @param ctx the parse tree
     */
    exitNamedExpressionSeq?: (ctx: NamedExpressionSeqContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.expression`.
     * @param ctx the parse tree
     */
    enterExpression?: (ctx: ExpressionContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.expression`.
     * @param ctx the parse tree
     */
    exitExpression?: (ctx: ExpressionContext) => void;
    /**
     * Enter a parse tree produced by the `logicalNot`
     * labeled alternative in `AntlrSQLParser.booleanExpression`.
     * @param ctx the parse tree
     */
    enterLogicalNot?: (ctx: LogicalNotContext) => void;
    /**
     * Exit a parse tree produced by the `logicalNot`
     * labeled alternative in `AntlrSQLParser.booleanExpression`.
     * @param ctx the parse tree
     */
    exitLogicalNot?: (ctx: LogicalNotContext) => void;
    /**
     * Enter a parse tree produced by the `exists`
     * labeled alternative in `AntlrSQLParser.booleanExpression`.
     * @param ctx the parse tree
     */
    enterExists?: (ctx: ExistsContext) => void;
    /**
     * Exit a parse tree produced by the `exists`
     * labeled alternative in `AntlrSQLParser.booleanExpression`.
     * @param ctx the parse tree
     */
    exitExists?: (ctx: ExistsContext) => void;
    /**
     * Enter a parse tree produced by the `predicated`
     * labeled alternative in `AntlrSQLParser.booleanExpression`.
     * @param ctx the parse tree
     */
    enterPredicated?: (ctx: PredicatedContext) => void;
    /**
     * Exit a parse tree produced by the `predicated`
     * labeled alternative in `AntlrSQLParser.booleanExpression`.
     * @param ctx the parse tree
     */
    exitPredicated?: (ctx: PredicatedContext) => void;
    /**
     * Enter a parse tree produced by the `logicalBinary`
     * labeled alternative in `AntlrSQLParser.booleanExpression`.
     * @param ctx the parse tree
     */
    enterLogicalBinary?: (ctx: LogicalBinaryContext) => void;
    /**
     * Exit a parse tree produced by the `logicalBinary`
     * labeled alternative in `AntlrSQLParser.booleanExpression`.
     * @param ctx the parse tree
     */
    exitLogicalBinary?: (ctx: LogicalBinaryContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.windowedAggregationClause`.
     * @param ctx the parse tree
     */
    enterWindowedAggregationClause?: (ctx: WindowedAggregationClauseContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.windowedAggregationClause`.
     * @param ctx the parse tree
     */
    exitWindowedAggregationClause?: (ctx: WindowedAggregationClauseContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.groupByClause`.
     * @param ctx the parse tree
     */
    enterGroupByClause?: (ctx: GroupByClauseContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.groupByClause`.
     * @param ctx the parse tree
     */
    exitGroupByClause?: (ctx: GroupByClauseContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.groupingSet`.
     * @param ctx the parse tree
     */
    enterGroupingSet?: (ctx: GroupingSetContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.groupingSet`.
     * @param ctx the parse tree
     */
    exitGroupingSet?: (ctx: GroupingSetContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.windowClause`.
     * @param ctx the parse tree
     */
    enterWindowClause?: (ctx: WindowClauseContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.windowClause`.
     * @param ctx the parse tree
     */
    exitWindowClause?: (ctx: WindowClauseContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.watermarkClause`.
     * @param ctx the parse tree
     */
    enterWatermarkClause?: (ctx: WatermarkClauseContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.watermarkClause`.
     * @param ctx the parse tree
     */
    exitWatermarkClause?: (ctx: WatermarkClauseContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.watermarkParameters`.
     * @param ctx the parse tree
     */
    enterWatermarkParameters?: (ctx: WatermarkParametersContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.watermarkParameters`.
     * @param ctx the parse tree
     */
    exitWatermarkParameters?: (ctx: WatermarkParametersContext) => void;
    /**
     * Enter a parse tree produced by the `timeBasedWindow`
     * labeled alternative in `AntlrSQLParser.windowSpec`.
     * @param ctx the parse tree
     */
    enterTimeBasedWindow?: (ctx: TimeBasedWindowContext) => void;
    /**
     * Exit a parse tree produced by the `timeBasedWindow`
     * labeled alternative in `AntlrSQLParser.windowSpec`.
     * @param ctx the parse tree
     */
    exitTimeBasedWindow?: (ctx: TimeBasedWindowContext) => void;
    /**
     * Enter a parse tree produced by the `countBasedWindow`
     * labeled alternative in `AntlrSQLParser.windowSpec`.
     * @param ctx the parse tree
     */
    enterCountBasedWindow?: (ctx: CountBasedWindowContext) => void;
    /**
     * Exit a parse tree produced by the `countBasedWindow`
     * labeled alternative in `AntlrSQLParser.windowSpec`.
     * @param ctx the parse tree
     */
    exitCountBasedWindow?: (ctx: CountBasedWindowContext) => void;
    /**
     * Enter a parse tree produced by the `thresholdBasedWindow`
     * labeled alternative in `AntlrSQLParser.windowSpec`.
     * @param ctx the parse tree
     */
    enterThresholdBasedWindow?: (ctx: ThresholdBasedWindowContext) => void;
    /**
     * Exit a parse tree produced by the `thresholdBasedWindow`
     * labeled alternative in `AntlrSQLParser.windowSpec`.
     * @param ctx the parse tree
     */
    exitThresholdBasedWindow?: (ctx: ThresholdBasedWindowContext) => void;
    /**
     * Enter a parse tree produced by the `tumblingWindow`
     * labeled alternative in `AntlrSQLParser.timeWindow`.
     * @param ctx the parse tree
     */
    enterTumblingWindow?: (ctx: TumblingWindowContext) => void;
    /**
     * Exit a parse tree produced by the `tumblingWindow`
     * labeled alternative in `AntlrSQLParser.timeWindow`.
     * @param ctx the parse tree
     */
    exitTumblingWindow?: (ctx: TumblingWindowContext) => void;
    /**
     * Enter a parse tree produced by the `slidingWindow`
     * labeled alternative in `AntlrSQLParser.timeWindow`.
     * @param ctx the parse tree
     */
    enterSlidingWindow?: (ctx: SlidingWindowContext) => void;
    /**
     * Exit a parse tree produced by the `slidingWindow`
     * labeled alternative in `AntlrSQLParser.timeWindow`.
     * @param ctx the parse tree
     */
    exitSlidingWindow?: (ctx: SlidingWindowContext) => void;
    /**
     * Enter a parse tree produced by the `countBasedTumbling`
     * labeled alternative in `AntlrSQLParser.countWindow`.
     * @param ctx the parse tree
     */
    enterCountBasedTumbling?: (ctx: CountBasedTumblingContext) => void;
    /**
     * Exit a parse tree produced by the `countBasedTumbling`
     * labeled alternative in `AntlrSQLParser.countWindow`.
     * @param ctx the parse tree
     */
    exitCountBasedTumbling?: (ctx: CountBasedTumblingContext) => void;
    /**
     * Enter a parse tree produced by the `thresholdWindow`
     * labeled alternative in `AntlrSQLParser.conditionWindow`.
     * @param ctx the parse tree
     */
    enterThresholdWindow?: (ctx: ThresholdWindowContext) => void;
    /**
     * Exit a parse tree produced by the `thresholdWindow`
     * labeled alternative in `AntlrSQLParser.conditionWindow`.
     * @param ctx the parse tree
     */
    exitThresholdWindow?: (ctx: ThresholdWindowContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.conditionParameter`.
     * @param ctx the parse tree
     */
    enterConditionParameter?: (ctx: ConditionParameterContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.conditionParameter`.
     * @param ctx the parse tree
     */
    exitConditionParameter?: (ctx: ConditionParameterContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.thresholdMinSizeParameter`.
     * @param ctx the parse tree
     */
    enterThresholdMinSizeParameter?: (ctx: ThresholdMinSizeParameterContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.thresholdMinSizeParameter`.
     * @param ctx the parse tree
     */
    exitThresholdMinSizeParameter?: (ctx: ThresholdMinSizeParameterContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.sizeParameter`.
     * @param ctx the parse tree
     */
    enterSizeParameter?: (ctx: SizeParameterContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.sizeParameter`.
     * @param ctx the parse tree
     */
    exitSizeParameter?: (ctx: SizeParameterContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.advancebyParameter`.
     * @param ctx the parse tree
     */
    enterAdvancebyParameter?: (ctx: AdvancebyParameterContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.advancebyParameter`.
     * @param ctx the parse tree
     */
    exitAdvancebyParameter?: (ctx: AdvancebyParameterContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.timeUnit`.
     * @param ctx the parse tree
     */
    enterTimeUnit?: (ctx: TimeUnitContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.timeUnit`.
     * @param ctx the parse tree
     */
    exitTimeUnit?: (ctx: TimeUnitContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.timestampParameter`.
     * @param ctx the parse tree
     */
    enterTimestampParameter?: (ctx: TimestampParameterContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.timestampParameter`.
     * @param ctx the parse tree
     */
    exitTimestampParameter?: (ctx: TimestampParameterContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.functionName`.
     * @param ctx the parse tree
     */
    enterFunctionName?: (ctx: FunctionNameContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.functionName`.
     * @param ctx the parse tree
     */
    exitFunctionName?: (ctx: FunctionNameContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.sinkClause`.
     * @param ctx the parse tree
     */
    enterSinkClause?: (ctx: SinkClauseContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.sinkClause`.
     * @param ctx the parse tree
     */
    exitSinkClause?: (ctx: SinkClauseContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.sink`.
     * @param ctx the parse tree
     */
    enterSink?: (ctx: SinkContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.sink`.
     * @param ctx the parse tree
     */
    exitSink?: (ctx: SinkContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.inlineSink`.
     * @param ctx the parse tree
     */
    enterInlineSink?: (ctx: InlineSinkContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.inlineSink`.
     * @param ctx the parse tree
     */
    exitInlineSink?: (ctx: InlineSinkContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.nullNotnull`.
     * @param ctx the parse tree
     */
    enterNullNotnull?: (ctx: NullNotnullContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.nullNotnull`.
     * @param ctx the parse tree
     */
    exitNullNotnull?: (ctx: NullNotnullContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.streamName`.
     * @param ctx the parse tree
     */
    enterStreamName?: (ctx: StreamNameContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.streamName`.
     * @param ctx the parse tree
     */
    exitStreamName?: (ctx: StreamNameContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.fileFormat`.
     * @param ctx the parse tree
     */
    enterFileFormat?: (ctx: FileFormatContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.fileFormat`.
     * @param ctx the parse tree
     */
    exitFileFormat?: (ctx: FileFormatContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.sortItem`.
     * @param ctx the parse tree
     */
    enterSortItem?: (ctx: SortItemContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.sortItem`.
     * @param ctx the parse tree
     */
    exitSortItem?: (ctx: SortItemContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.predicate`.
     * @param ctx the parse tree
     */
    enterPredicate?: (ctx: PredicateContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.predicate`.
     * @param ctx the parse tree
     */
    exitPredicate?: (ctx: PredicateContext) => void;
    /**
     * Enter a parse tree produced by the `functionCall`
     * labeled alternative in `AntlrSQLParser.valueExpression`.
     * @param ctx the parse tree
     */
    enterFunctionCall?: (ctx: FunctionCallContext) => void;
    /**
     * Exit a parse tree produced by the `functionCall`
     * labeled alternative in `AntlrSQLParser.valueExpression`.
     * @param ctx the parse tree
     */
    exitFunctionCall?: (ctx: FunctionCallContext) => void;
    /**
     * Enter a parse tree produced by the `arithmeticUnary`
     * labeled alternative in `AntlrSQLParser.valueExpression`.
     * @param ctx the parse tree
     */
    enterArithmeticUnary?: (ctx: ArithmeticUnaryContext) => void;
    /**
     * Exit a parse tree produced by the `arithmeticUnary`
     * labeled alternative in `AntlrSQLParser.valueExpression`.
     * @param ctx the parse tree
     */
    exitArithmeticUnary?: (ctx: ArithmeticUnaryContext) => void;
    /**
     * Enter a parse tree produced by the `valueExpressionDefault`
     * labeled alternative in `AntlrSQLParser.valueExpression`.
     * @param ctx the parse tree
     */
    enterValueExpressionDefault?: (ctx: ValueExpressionDefaultContext) => void;
    /**
     * Exit a parse tree produced by the `valueExpressionDefault`
     * labeled alternative in `AntlrSQLParser.valueExpression`.
     * @param ctx the parse tree
     */
    exitValueExpressionDefault?: (ctx: ValueExpressionDefaultContext) => void;
    /**
     * Enter a parse tree produced by the `arithmeticBinary`
     * labeled alternative in `AntlrSQLParser.valueExpression`.
     * @param ctx the parse tree
     */
    enterArithmeticBinary?: (ctx: ArithmeticBinaryContext) => void;
    /**
     * Exit a parse tree produced by the `arithmeticBinary`
     * labeled alternative in `AntlrSQLParser.valueExpression`.
     * @param ctx the parse tree
     */
    exitArithmeticBinary?: (ctx: ArithmeticBinaryContext) => void;
    /**
     * Enter a parse tree produced by the `comparison`
     * labeled alternative in `AntlrSQLParser.valueExpression`.
     * @param ctx the parse tree
     */
    enterComparison?: (ctx: ComparisonContext) => void;
    /**
     * Exit a parse tree produced by the `comparison`
     * labeled alternative in `AntlrSQLParser.valueExpression`.
     * @param ctx the parse tree
     */
    exitComparison?: (ctx: ComparisonContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.comparisonOperator`.
     * @param ctx the parse tree
     */
    enterComparisonOperator?: (ctx: ComparisonOperatorContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.comparisonOperator`.
     * @param ctx the parse tree
     */
    exitComparisonOperator?: (ctx: ComparisonOperatorContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.hint`.
     * @param ctx the parse tree
     */
    enterHint?: (ctx: HintContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.hint`.
     * @param ctx the parse tree
     */
    exitHint?: (ctx: HintContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.hintStatement`.
     * @param ctx the parse tree
     */
    enterHintStatement?: (ctx: HintStatementContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.hintStatement`.
     * @param ctx the parse tree
     */
    exitHintStatement?: (ctx: HintStatementContext) => void;
    /**
     * Enter a parse tree produced by the `star`
     * labeled alternative in `AntlrSQLParser.primaryExpression`.
     * @param ctx the parse tree
     */
    enterStar?: (ctx: StarContext) => void;
    /**
     * Exit a parse tree produced by the `star`
     * labeled alternative in `AntlrSQLParser.primaryExpression`.
     * @param ctx the parse tree
     */
    exitStar?: (ctx: StarContext) => void;
    /**
     * Enter a parse tree produced by the `subqueryExpression`
     * labeled alternative in `AntlrSQLParser.primaryExpression`.
     * @param ctx the parse tree
     */
    enterSubqueryExpression?: (ctx: SubqueryExpressionContext) => void;
    /**
     * Exit a parse tree produced by the `subqueryExpression`
     * labeled alternative in `AntlrSQLParser.primaryExpression`.
     * @param ctx the parse tree
     */
    exitSubqueryExpression?: (ctx: SubqueryExpressionContext) => void;
    /**
     * Enter a parse tree produced by the `rowConstructor`
     * labeled alternative in `AntlrSQLParser.primaryExpression`.
     * @param ctx the parse tree
     */
    enterRowConstructor?: (ctx: RowConstructorContext) => void;
    /**
     * Exit a parse tree produced by the `rowConstructor`
     * labeled alternative in `AntlrSQLParser.primaryExpression`.
     * @param ctx the parse tree
     */
    exitRowConstructor?: (ctx: RowConstructorContext) => void;
    /**
     * Enter a parse tree produced by the `parenthesizedExpression`
     * labeled alternative in `AntlrSQLParser.primaryExpression`.
     * @param ctx the parse tree
     */
    enterParenthesizedExpression?: (ctx: ParenthesizedExpressionContext) => void;
    /**
     * Exit a parse tree produced by the `parenthesizedExpression`
     * labeled alternative in `AntlrSQLParser.primaryExpression`.
     * @param ctx the parse tree
     */
    exitParenthesizedExpression?: (ctx: ParenthesizedExpressionContext) => void;
    /**
     * Enter a parse tree produced by the `constantDefault`
     * labeled alternative in `AntlrSQLParser.primaryExpression`.
     * @param ctx the parse tree
     */
    enterConstantDefault?: (ctx: ConstantDefaultContext) => void;
    /**
     * Exit a parse tree produced by the `constantDefault`
     * labeled alternative in `AntlrSQLParser.primaryExpression`.
     * @param ctx the parse tree
     */
    exitConstantDefault?: (ctx: ConstantDefaultContext) => void;
    /**
     * Enter a parse tree produced by the `columnReference`
     * labeled alternative in `AntlrSQLParser.primaryExpression`.
     * @param ctx the parse tree
     */
    enterColumnReference?: (ctx: ColumnReferenceContext) => void;
    /**
     * Exit a parse tree produced by the `columnReference`
     * labeled alternative in `AntlrSQLParser.primaryExpression`.
     * @param ctx the parse tree
     */
    exitColumnReference?: (ctx: ColumnReferenceContext) => void;
    /**
     * Enter a parse tree produced by the `dereference`
     * labeled alternative in `AntlrSQLParser.primaryExpression`.
     * @param ctx the parse tree
     */
    enterDereference?: (ctx: DereferenceContext) => void;
    /**
     * Exit a parse tree produced by the `dereference`
     * labeled alternative in `AntlrSQLParser.primaryExpression`.
     * @param ctx the parse tree
     */
    exitDereference?: (ctx: DereferenceContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.qualifiedName`.
     * @param ctx the parse tree
     */
    enterQualifiedName?: (ctx: QualifiedNameContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.qualifiedName`.
     * @param ctx the parse tree
     */
    exitQualifiedName?: (ctx: QualifiedNameContext) => void;
    /**
     * Enter a parse tree produced by the `integerLiteral`
     * labeled alternative in `AntlrSQLParser.number`.
     * @param ctx the parse tree
     */
    enterIntegerLiteral?: (ctx: IntegerLiteralContext) => void;
    /**
     * Exit a parse tree produced by the `integerLiteral`
     * labeled alternative in `AntlrSQLParser.number`.
     * @param ctx the parse tree
     */
    exitIntegerLiteral?: (ctx: IntegerLiteralContext) => void;
    /**
     * Enter a parse tree produced by the `floatLiteral`
     * labeled alternative in `AntlrSQLParser.number`.
     * @param ctx the parse tree
     */
    enterFloatLiteral?: (ctx: FloatLiteralContext) => void;
    /**
     * Exit a parse tree produced by the `floatLiteral`
     * labeled alternative in `AntlrSQLParser.number`.
     * @param ctx the parse tree
     */
    exitFloatLiteral?: (ctx: FloatLiteralContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.unsignedIntegerLiteral`.
     * @param ctx the parse tree
     */
    enterUnsignedIntegerLiteral?: (ctx: UnsignedIntegerLiteralContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.unsignedIntegerLiteral`.
     * @param ctx the parse tree
     */
    exitUnsignedIntegerLiteral?: (ctx: UnsignedIntegerLiteralContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.signedIntegerLiteral`.
     * @param ctx the parse tree
     */
    enterSignedIntegerLiteral?: (ctx: SignedIntegerLiteralContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.signedIntegerLiteral`.
     * @param ctx the parse tree
     */
    exitSignedIntegerLiteral?: (ctx: SignedIntegerLiteralContext) => void;
    /**
     * Enter a parse tree produced by the `nullLiteral`
     * labeled alternative in `AntlrSQLParser.constant`.
     * @param ctx the parse tree
     */
    enterNullLiteral?: (ctx: NullLiteralContext) => void;
    /**
     * Exit a parse tree produced by the `nullLiteral`
     * labeled alternative in `AntlrSQLParser.constant`.
     * @param ctx the parse tree
     */
    exitNullLiteral?: (ctx: NullLiteralContext) => void;
    /**
     * Enter a parse tree produced by the `typeConstructor`
     * labeled alternative in `AntlrSQLParser.constant`.
     * @param ctx the parse tree
     */
    enterTypeConstructor?: (ctx: TypeConstructorContext) => void;
    /**
     * Exit a parse tree produced by the `typeConstructor`
     * labeled alternative in `AntlrSQLParser.constant`.
     * @param ctx the parse tree
     */
    exitTypeConstructor?: (ctx: TypeConstructorContext) => void;
    /**
     * Enter a parse tree produced by the `numericLiteral`
     * labeled alternative in `AntlrSQLParser.constant`.
     * @param ctx the parse tree
     */
    enterNumericLiteral?: (ctx: NumericLiteralContext) => void;
    /**
     * Exit a parse tree produced by the `numericLiteral`
     * labeled alternative in `AntlrSQLParser.constant`.
     * @param ctx the parse tree
     */
    exitNumericLiteral?: (ctx: NumericLiteralContext) => void;
    /**
     * Enter a parse tree produced by the `booleanLiteral`
     * labeled alternative in `AntlrSQLParser.constant`.
     * @param ctx the parse tree
     */
    enterBooleanLiteral?: (ctx: BooleanLiteralContext) => void;
    /**
     * Exit a parse tree produced by the `booleanLiteral`
     * labeled alternative in `AntlrSQLParser.constant`.
     * @param ctx the parse tree
     */
    exitBooleanLiteral?: (ctx: BooleanLiteralContext) => void;
    /**
     * Enter a parse tree produced by the `stringLiteral`
     * labeled alternative in `AntlrSQLParser.constant`.
     * @param ctx the parse tree
     */
    enterStringLiteral?: (ctx: StringLiteralContext) => void;
    /**
     * Exit a parse tree produced by the `stringLiteral`
     * labeled alternative in `AntlrSQLParser.constant`.
     * @param ctx the parse tree
     */
    exitStringLiteral?: (ctx: StringLiteralContext) => void;
    /**
     * Enter a parse tree produced by `AntlrSQLParser.booleanValue`.
     * @param ctx the parse tree
     */
    enterBooleanValue?: (ctx: BooleanValueContext) => void;
    /**
     * Exit a parse tree produced by `AntlrSQLParser.booleanValue`.
     * @param ctx the parse tree
     */
    exitBooleanValue?: (ctx: BooleanValueContext) => void;

    visitTerminal(node: TerminalNode): void {}
    visitErrorNode(node: ErrorNode): void {}
    enterEveryRule(node: ParserRuleContext): void {}
    exitEveryRule(node: ParserRuleContext): void {}
}

