# This is the config file for the GitHub reviewer lottery action
# You can specify the groups and the usernames of the reviewers

groups:
  - name: maintainer
    reviewers: 1 # how many reviewers do you want to assign
    usernames: # GitHub usernames of the reviewers
      - zeuchste
      - keyseven123
      - adrianmichalke
      - alepping
      - ls-1801
