CREATE WORKER 'localhost:8080';
CREATE LOGICAL SOURCE gen(ts UINT64 NOT NULL);
CREATE PHYSICAL SOURCE FOR gen TYPE Generator SET(
    'CSV' AS INPUT_FORMATTER."TYPE",
    'localhost:8080' AS "SOURCE".HOST,
    'ALL' AS "SOURCE".STOP_GENERATOR_WHEN_SEQUENCE_FINISHES,
    1 AS "SOURCE".SEED,
    10000000 AS "SOURCE".MAX_RUNTIME_MS,
    'emit_rate 5' AS "SOURCE".GENERATOR_RATE_CONFIG,
    'SEQUENCE UINT64 0 10000000 1' AS "SOURCE".GENERATOR_SCHEMA);
CREATE SINK out(ts UINT64 NOT NULL) TYPE File SET('localhost:8080' AS "SINK".HOST, '/tmp/persist.csv' AS "SINK".FILE_PATH, 'CSV' AS "SINK".OUTPUT_FORMAT);
SELECT ts FROM gen INTO out SET ('aaaaaaaa-1111-2222-3333-444444444444' AS "QUERY"."ID");
