#ifndef NES_INCLUDE_QUERYCOMPILER_GENERATABLEOPERATORS_GENERATABLEOPERATORFORWARDREF_HPP_
#define NES_INCLUDE_QUERYCOMPILER_GENERATABLEOPERATORS_GENERATABLEOPERATORFORWARDREF_HPP_

#include <memory>
namespace NES {

class GeneratableFilterOperator;
typedef std::shared_ptr<GeneratableFilterOperator> GeneratableFilterOperatorPtr;

class GeneratableMapOperator;
typedef std::shared_ptr<GeneratableMapOperator> GeneratableMapOperatorPtr;

class GeneratableMergeOperator;
typedef std::shared_ptr<GeneratableMergeOperator> GeneratableMergeOperatorPtr;

class GeneratableCompleteWindowOperator;
typedef std::shared_ptr<GeneratableCompleteWindowOperator> GeneratableWindowOperatorPtr;

class GeneratableSlicingWindowOperator;
typedef std::shared_ptr<GeneratableSlicingWindowOperator> GeneratableDistributedlWindowSliceCreationOperatorPtr;

class GeneratableCombiningWindowOperator;
typedef std::shared_ptr<GeneratableCombiningWindowOperator> GeneratableDistributedlWindowCombinerOperatorPtr;

class GeneratableSinkOperator;
typedef std::shared_ptr<GeneratableSinkOperator> GeneratableSinkOperatorPtr;

class GeneratableSourceOperator;
typedef std::shared_ptr<GeneratableSourceOperator> GeneratableSourceOperatorPtr;

class GeneratableScanOperator;
typedef std::shared_ptr<GeneratableScanOperator> GeneratableScanOperatorPtr;

class GeneratableWatermarkAssignerOperator;
typedef std::shared_ptr<GeneratableWatermarkAssignerOperator> GeneratableWatermarkAssignerOperatorPtr;

}// namespace NES

#endif//NES_INCLUDE_QUERYCOMPILER_GENERATABLEOPERATORS_GENERATABLEOPERATORFORWARDREF_HPP_
