#ifndef INCLUDE_GENERATEDQUERYEXECUTIONPLAN_H_
#define INCLUDE_GENERATEDQUERYEXECUTIONPLAN_H_

#include <NodeEngine/BufferManager.hpp>
#include <QueryCompiler/PipelineStage.hpp>
#include <QueryCompiler/QueryExecutionPlan.hpp>

namespace NES {
class GeneratedQueryExecutionPlan;
typedef std::shared_ptr<GeneratedQueryExecutionPlan> GeneratedQueryExecutionPlanPtr;

/**
 * @brief this class represent a query execution plan generated by the compiler.
 * Invariant: this class is thread-safe
 */
class GeneratedQueryExecutionPlan : public QueryExecutionPlan {
  public:
    explicit GeneratedQueryExecutionPlan(QueryExecutionPlanId queryId,
                                         std::vector<DataSourcePtr> sources,
                                         std::vector<PipelineStagePtr> stages,
                                         QueryManagerPtr queryManager,
                                         BufferManagerPtr bufferManager);
};

}// namespace NES
#endif /* INCLUDE_GENERATEDQUERYEXECUTIONPLAN_H_ */
