#ifndef NES_IMPL_OPTIMIZER_QUERYREWRITE_BASERULE_HPP_
#define NES_IMPL_OPTIMIZER_QUERYREWRITE_BASERULE_HPP_

namespace NES {

class BaseRewriteRule {

  public:

};
}

#endif //NES_IMPL_OPTIMIZER_QUERYREWRITE_BASERULE_HPP_
