#ifndef NES_IMPL_OPTIMIZER_QUERYREWRITE_FILTERPUSHDOWN_HPP_
#define NES_IMPL_OPTIMIZER_QUERYREWRITE_FILTERPUSHDOWN_HPP_

namespace NES {

class FilterPushDownRule {

};

}

#endif //NES_IMPL_OPTIMIZER_QUERYREWRITE_FILTERPUSHDOWN_HPP_
