#ifndef UTILITY_FUNCTIONS_HPP
#define UTILITY_FUNCTIONS_HPP

#include <API/Query.hpp>
#include <string>

/**
 * @brief a collection of shared utility functions
 */
namespace NES {
class StreamCatalog;
typedef std::shared_ptr<StreamCatalog> StreamCatalogPtr;

class UtilityFunctions {
  public:
    // removes leading and trailing whitespaces
    static std::string trim(std::string s);

    /**
   *  @brief this function **executes** the code provided by the user and returns an InputQuery Object
   *  @caution: this function will replace the stream name "xyz" provided by the user with the stream generated by the system and fetched from the catalog
   *  @param query as a string
   *  @return Smart pointer to InputQuery object of the query
   *  */
    static QueryPtr createQueryFromCodeString(
        const std::string& query_code_snippet);

    /**
   *  @brief this function **executes** the code provided by the user and returns an schema Object
   *  @param query as a string
   *  @return Smart pointer to InputQuery object of the query
   *  */
    static SchemaPtr createSchemaFromCode(const std::string& query_code_snippet);

    /**
   * @brief this function creates an ID string
   * @return the ID string
   * https://stackoverflow.com/questions/24365331/how-can-i-generate-uuid-in-c-without-using-boost-library
   * example id: 665b3caf-f097-568e-2b2f-220b6c0a9bcd
   */
    static std::string generateIdString();

    /**
  * @brief this function creates a hased ID as int
  * @return the ID as site_t
  */
   static std::size_t generateIdInt();

   /**
   * @brief get the first substring between a unique first delimiter and a non-unique second delimiter
   * @param input
   * @param delimiter1
   * @param delimiter2
   * @return the substring
   */
   static std::string getFirstStringBetweenTwoDelimiters(const std::string& input, std::string s1, std::string s2);

   /**
     * @brief Outputs a tuple buffer accordingly to a specific schema
     * @param buffer the tuple buffer
     * @param schema  the schema
     * @return
     */
   static std::string prettyPrintTupleBuffer(TupleBuffer& buffer, SchemaPtr schema);
};
}// namespace NES

#endif /* UTILITY_FUNCTIONS_HPP */
