/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#include <SemanticMapCodec.hpp>

#include <algorithm>
#include <span>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include <ErrorHandling.hpp>
#include <ResponseParsing.hpp>
#include <SemanticModelCatalog.hpp>
#include <SemanticPromptLayout.hpp>
#include <SemanticRowPayload.hpp>

namespace NES
{

SemanticMapCodec::SemanticMapCodec(SemanticModelConfig config) : config(std::move(config))
{
    PRECONDITION(!this->config.steps.empty(), "SemanticMapCodec needs at least one step");
    PRECONDITION(
        std::ranges::all_of(this->config.steps, [](const SemanticStep& step) { return step.kind == SemanticStep::Kind::MAP; }),
        "SemanticMapCodec handles MAP steps only; a step list with a FILTER step belongs to SemanticFilterCodec");
}

std::string SemanticMapCodec::buildPrompt(const std::span<const RowPayload> rows) const
{
    return detail::buildFusedPrompt(config, rows);
}

std::vector<std::vector<std::string>> SemanticMapCodec::parse(const std::string_view response, const std::span<const RowPayload> rows) const
{
    const auto parsed = parseLlmJson(response);

    std::vector<std::vector<std::string>> answers;
    answers.reserve(rows.size());
    for (const auto& row : rows)
    {
        /// Row ids are generated by the codec itself, so they are matched exactly.
        const nlohmann::json* const rowData = parsed.is_object() && parsed.contains(row.rowId) ? &parsed.at(row.rowId) : nullptr;

        auto& rowAnswers = answers.emplace_back();
        rowAnswers.reserve(config.steps.size());
        for (const auto& step : config.steps)
        {
            rowAnswers.push_back(detail::mapAnswer(rowData, step, step.outputColumn, row.rowId, response));
        }
    }
    return answers;
}

}
