/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#include <SemanticFilterCodec.hpp>

#include <algorithm>
#include <cstddef>
#include <span>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

#include <fmt/format.h>
#include <nlohmann/json.hpp>

#include <Util/Logger/Logger.hpp>
#include <ErrorHandling.hpp>
#include <ResponseParsing.hpp>
#include <SemanticModelCatalog.hpp>
#include <SemanticPromptLayout.hpp>
#include <SemanticRowPayload.hpp>

namespace NES
{

namespace
{

/// `self.sysprompt` of `Llm_operator`, which `_filter_with_llm` sends unchanged. The typographic
/// apostrophe in "user’s" is part of the reference and goes out as UTF-8.
constexpr std::string_view BaseSysprompt
    = "You are a helpful AI assistant for semantic data operations.\n"
      "Always respond in JSON format.\n"
      "The response must have one key for each input row (_llm_call_id), and the value must be a JSON object with the answer and a "
      "confidence score between 0 and 1.\n"
      "Example output: {\n"
      "  \"row1\": {\"answer\": true, \"confidence\": 0.95},\n"
      "  \"row2\": {\"answer\": false, \"confidence\": 0.80}\n"
      "}\n"
      "Structure of the prompt:\n"
      "1. Operator prompt: The operator-specific instruction.\n"
      "2. User instructions: The user’s task or question.\n"
      "3. Dataset context (optional): background/domain description of the input dataset.\n"
      "4. Data: Input data, always in JSON format. Each data item (row) is a JSON object and always includes a unique row id field "
      "named _llm_call_id.\n"
      "Input data example: [ {\"_llm_call_id\": \"row1\", ...}, {\"_llm_call_id\": \"row2\", ...} ]\n"
      "Do not add explanations.";

/// The verdict a row or column entry carries. The reference reads `answer` from an object and takes
/// any other value as the verdict itself (`bool(result)`); a missing `answer` is falsy.
bool verdictOf(const nlohmann::json& entry)
{
    if (entry.is_object())
    {
        const auto answer = entry.find("answer");
        return answer != entry.end() && isAffirmative(*answer);
    }
    return isAffirmative(entry);
}

}

SemanticFilterCodec::SemanticFilterCodec(SemanticModelConfig config)
    : config(std::move(config))
    , filterOnly(std::ranges::all_of(this->config.steps, [](const SemanticStep& step) { return step.kind == SemanticStep::Kind::FILTER; }))
    , columns(detail::stepResponseColumns(this->config.steps))
{
    PRECONDITION(
        std::ranges::any_of(this->config.steps, [](const SemanticStep& step) { return step.kind == SemanticStep::Kind::FILTER; }),
        "SemanticFilterCodec needs at least one FILTER step");
}

std::string SemanticFilterCodec::buildPrompt(const std::span<const RowPayload> rows) const
{
    if (!filterOnly)
    {
        return detail::buildFusedPrompt(config, rows);
    }

    std::string operatorPrompt;
    if (config.steps.size() == 1)
    {
        operatorPrompt = fmt::format("Filter rows: {}", config.steps.front().prompt);
    }
    else
    {
        operatorPrompt = "Filter rows that satisfy ALL of the following conditions:\n";
        for (size_t i = 0; i < config.steps.size(); ++i)
        {
            operatorPrompt += fmt::format("  {}. {}\n", i + 1, config.steps[i].prompt);
        }
        operatorPrompt += "A row passes only if ALL conditions are true.";
    }

    auto prompt = fmt::format("{}\n{}\n", BaseSysprompt, operatorPrompt);
    prompt += detail::datasetContextBlock(config);
    detail::appendDataBlock(prompt, rows, config.payloadFormat);
    return prompt;
}

std::vector<FilterRowResult> SemanticFilterCodec::parse(const std::string_view response, const std::span<const RowPayload> rows) const
{
    const auto parsed = parseLlmJson(response);

    std::vector<FilterRowResult> results;
    results.reserve(rows.size());
    for (const auto& row : rows)
    {
        /// Row ids are generated by the codec itself, so they are matched exactly.
        const nlohmann::json* const rowData = parsed.is_object() && parsed.contains(row.rowId) ? &parsed.at(row.rowId) : nullptr;
        auto& result = results.emplace_back();

        if (filterOnly)
        {
            /// One verdict per row covers every condition: the prompt asks for ALL of them at once.
            result.passed = rowData != nullptr && verdictOf(*rowData);
        }
        else
        {
            result.passed = true;
            for (size_t step = 0; step < config.steps.size(); ++step)
            {
                if (config.steps[step].kind == SemanticStep::Kind::FILTER)
                {
                    const auto* const verdict = rowData != nullptr ? findMember(*rowData, columns[step]) : nullptr;
                    result.passed = result.passed && verdict != nullptr && verdictOf(*verdict);
                }
                else
                {
                    result.mapAnswers.push_back(detail::mapAnswer(rowData, config.steps[step], columns[step], row.rowId, response));
                }
            }
        }
        if (!result.passed)
        {
            NES_TRACE("Semantic filter drops row {}", row.rowId);
        }
    }
    return results;
}

}
