type: Generator
stop_generator_when_sequence_finishes: ALL
max_runtime_ms: 1000000
generator_rate_type: SINUS
generator_rate_config: |
  amplitude 1000
  frequency 2
seed: 1
generator_schema: |
  SEQUENCE UINT64 0 10000 1
  SEQUENCE UINT64 0 100 1
