type: TCP
numberOfBuffersInLocalPool: 16
socketDomain: AF_INET
socketType: SOCK_STREAM
socketPort: PLACEHOLDER
socketHost: PLACEHOLDER
socketBufferSize: 2
flushIntervalMS: 100
connectTimeoutSeconds: 60
