FROM ubuntu:20.04

COPY toolchain-aarch64-llvm.cmake toolchain-aarch64-llvm.cmake
COPY toolchain-aarch64-gcc.cmake toolchain-aarch64-gcc.cmake
COPY nesCoordinator nesCoordinator
COPY nesWorker nesWorker

RUN mkdir -p /opt/toolchain && \
cp toolchain-aarch64-llvm.cmake /opt/toolchain/toolchain-aarch64-llvm.cmake && \
cp toolchain-aarch64-gcc.cmake /opt/toolchain/toolchain-aarch64-gcc.cmake

RUN sed -i -- 's|deb http|deb [arch=amd64] http|g' /etc/apt/sources.list && \
cp /etc/apt/sources.list /etc/apt/sources.list.d/ports.list && \
sed -i -- 's|amd64|arm64|g' /etc/apt/sources.list.d/ports.list && \
sed -i -E -- 's|http://.*archive\.ubuntu\.com/ubuntu|http://ports.ubuntu.com/ubuntu-ports|g' /etc/apt/sources.list.d/ports.list && \
sed -i -E -- 's|http://.*security\.ubuntu\.com/ubuntu|http://ports.ubuntu.com/ubuntu-ports|g' /etc/apt/sources.list.d/ports.list && \
dpkg --add-architecture arm64 && \
apt-get update

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --no-install-recommends -o APT::Immediate-Configure=false -qq \
  build-essential \
  ca-certificates \
  clang \
  clang-format \
  lld \
  llvm \
  llvm-dev \
  libssl-dev \
  libmbedtls-dev \
  crossbuild-essential-arm64 \
  libstdc++6-arm64-cross \
  qemu-user \
  cmake \
  git \
  python3-dev \
  python-dev \
  gdb \
  libc++-dev:arm64 \
  libstdc++-9-dev:arm64 \
  libpython3-dev:arm64 \
  libncurses5-dev:arm64 \
  libxml2-dev:arm64 \
  libedit-dev:arm64 \
  libdwarf-dev:arm64 \
  libdw-dev:arm64 \
  liblog4cxx-dev:arm64 \
  librdkafka1:arm64 \
  librdkafka++1:arm64 \
  librdkafka-dev:arm64 \
  libssl-dev:arm64 \
  libmbedtls-dev:arm64 \
  libeigen3-dev:arm64 \
  libzmqpp-dev:arm64 \
  z3:arm64 \
  doxygen:arm64 \
  graphviz:arm64 \
  libz3-dev:arm64 && \
  libjemalloc-dev:arm64 \
  apt-get clean -qq

RUN mkdir -p /opt/sysroots/aarch64-linux-gnu/usr && \
mkdir -p /opt/toolchain && \
cd /opt/sysroots/aarch64-linux-gnu/usr && \
cp -r -v -L /usr/aarch64-linux-gnu/include /usr/aarch64-linux-gnu/lib . && cd lib && \
cp -r -v -L /usr/lib/gcc-cross/aarch64-linux-gnu/9/*gcc* . && \
cp -r -v -L /usr/lib/gcc-cross/aarch64-linux-gnu/9/*crt* . && \
cp -r -v -L /usr/lib/gcc-cross/aarch64-linux-gnu/9/libsupc++.a . && \
cp -r -v -L /usr/lib/gcc-cross/aarch64-linux-gnu/9/libstdc++*  . && cd

RUN git config --global advice.detachedHead false && \
(git clone --quiet --single-branch --recursive https://github.com/boostorg/boost && cd boost && \
rm -rf more && git checkout boost-1.71.0 && ./bootstrap.sh && \
sed -i -- 's|using gcc ;|using gcc : arm64 : aarch64-linux-gnu-g++ ;|g' project-config.jam && \
./b2 install -j2 toolset=gcc-arm64 --prefix=/opt/sysroots/aarch64-linux-gnu/usr) || cd .. || rm -rf boost

RUN cd && git clone https://github.com/open62541/open62541.git && cd open62541 && \
git submodule update --init --recursive && mkdir -p build && cd build && \
cmake .. -DBUILD_SHARED_LIBS=1 \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DUA_NAMESPACE_ZERO=FULL \
    -DCMAKE_TOOLCHAIN_FILE=/opt/toolchain/toolchain-aarch64-gcc.cmake && \
make -j2 && make install && cd && rm -rf open62541

RUN cd ${HOME} && git clone https://github.com/eclipse/paho.mqtt.c.git && \
  cd paho.mqtt.c && git checkout v1.3.8 && \
  cmake -Bbuild -H. -DPAHO_ENABLE_TESTING=OFF \
  -DPAHO_BUILD_STATIC=ON \
  -DPAHO_WITH_SSL=ON \
  -DPAHO_HIGH_PERFORMANCE=ON \
  -DCMAKE_TOOLCHAIN_FILE=/opt/toolchain/toolchain-aarch64-gcc.cmake && \
  cmake --build build/ --target install && \
  ldconfig && cd ${HOME} && rm -rf paho.mqtt.c && \
  git clone https://github.com/eclipse/paho.mqtt.cpp && cd paho.mqtt.cpp && \
  cmake -Bbuild -H. -DPAHO_BUILD_STATIC=ON -DPAHO_BUILD_DOCUMENTATION=TRUE -DPAHO_BUILD_SAMPLES=TRUE \
  -DCMAKE_TOOLCHAIN_FILE=/opt/toolchain/toolchain-aarch64-gcc.cmake && \
  cmake --build build/ --target install && ldconfig && cd ${HOME} && rm -rf paho.mqtt.cpp

RUN cd /opt/sysroots/aarch64-linux-gnu/usr && \
cp -r -v -L /usr/aarch64-linux-gnu/include /usr/aarch64-linux-gnu/lib . && \
cp -r -v -L /usr/include/z3* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/zmq* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/log4* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/libdwarf* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/dwarf* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/elfutils* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/pplx* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/aarch64-linux-gnu/openssl* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/openssl* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/aarch64-linux-gnu/c++/9* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/c++/9* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/gelf* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/libelf* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/nlist* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/local/include/open62541* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/local/include/aa_tree* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/local/include/ziptree* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/local/include/ms_stdint* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/librdkafka* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/libpaho-mqttpp3* /opt/sysroots/aarch64-linux-gnu/include/ && \
cp -r -v -L /usr/include/libpaho-mqtt3as* /opt/sysroots/aarch64-linux-gnu/include/ && \
cp -r -v -L /usr/include/boost/graph/graphviz* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/jemalloc* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/mbedtls* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/lib/aarch64-linux-gnu/libz3* /opt/sysroots/aarch64-linux-gnu/usr/lib/ && \
cp -r -v -L /usr/lib/aarch64-linux-gnu/libzmq* /opt/sysroots/aarch64-linux-gnu/usr/lib/ && \
cp -r -v -L /usr/lib/aarch64-linux-gnu/liblog4* /opt/sysroots/aarch64-linux-gnu/usr/lib/ && \
cp -r -v -L /usr/lib/aarch64-linux-gnu/libdwarf* /opt/sysroots/aarch64-linux-gnu/usr/lib/ && \
cp -r -v -L /usr/lib/aarch64-linux-gnu/libdw* /opt/sysroots/aarch64-linux-gnu/usr/lib/ && \
cp -r -v -L /usr/lib/aarch64-linux-gnu/libebl* /opt/sysroots/aarch64-linux-gnu/usr/lib/ && \
cp -r -v -L /usr/lib/aarch64-linux-gnu/libcrypto* /opt/sysroots/aarch64-linux-gnu/usr/lib/ && \
cp -r -v -L /usr/lib/aarch64-linux-gnu/libssl* /opt/sysroots/aarch64-linux-gnu/usr/lib/ && \
cp -r -v -L /usr/lib/x86_64-linux-gnu/graphviz* /opt/sysroots/aarch64-linux-gnu/usr/lib/ && \
cp -r -v -L -fd /usr/lib/llvm-10* /opt/sysroots/aarch64-linux-gnu/usr/lib/ && \
cp -r -v -L /usr/lib/gcc/aarch64-linux-gnu/9* /opt/sysroots/aarch64-linux-gnu/usr/lib/ && \
cp -r -v -L /usr/lib/aarch64-linux-gnu/libelf* /opt/sysroots/aarch64-linux-gnu/usr/lib/ && \
cp -r -v -L /usr/lib/aarch64-linux-gnu/libpaho-mqttpp3* /opt/sysroots/aarch64-linux-gnu/lib/ && \
cp -r -v -L /usr/lib/aarch64-linux-gnu/libpaho-mqtt3as* /opt/sysroots/aarch64-linux-gnu/lib/ && \
cp -r -v -L /usr/local/lib/libopen62541* /opt/sysroots/aarch64-linux-gnu/usr/lib/ && \
cp -r -v -L /usr/local/lib/cmake/open62541* /opt/sysroots/aarch64-linux-gnu/usr/lib/cmake/ && \
cp -r -v -L /usr/lib/aarch64-linux-gnu/librdkafka* /opt/sysroots/aarch64-linux-gnu/usr/lib/ && \
cp -r -v -L /usr/lib/aarch64-linux-gnu/libmbed* /opt/sysroots/aarch64-linux-gnu/usr/lib/ && \
cp -r -v -L /usr/lib/aarch64-linux-gnu/libjemalloc* /opt/sysroots/aarch64-linux-gnu/usr/lib/ && \
cp -r -v -L /usr/lib/aarch64-linux-gnu/pkgconfig/jemalloc* /opt/sysroots/aarch64-linux-gnu/usr/lib/pkgconfig/ && \
cp -r -v -L /usr/lib/aarch64-linux-gnu/libmbed* /opt/sysroots/aarch64-linux-gnu/usr/lib/

RUN cd && git clone --branch v1.28.1 https://github.com/grpc/grpc.git && \
cd grpc && git submodule update --init --recursive --jobs 1 && mkdir -p build && cd build && \
cmake .. -DCMAKE_BUILD_TYPE=Release -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF -DgRPC_SSL_PROVIDER=package && \
make -j2 install && cd .. && rm -rf build && mkdir -p build && cd build && \
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/opt/toolchain/toolchain-aarch64-gcc.cmake \
-DCMAKE_INSTALL_PREFIX=/opt/sysroots/aarch64-linux-gnu/ && \
make -j2 install && cd ../.. && rm -rf grpc

RUN cd ${HOME} && git clone https://github.com/eclipse/paho.mqtt.c.git && \
  cd paho.mqtt.c && git checkout v1.3.8 && \
  cmake -Bbuild -H. -DPAHO_ENABLE_TESTING=OFF \
  -DPAHO_BUILD_STATIC=ON \
  -DPAHO_WITH_SSL=ON \
  -DPAHO_HIGH_PERFORMANCE=ON && \
  cmake --build build/ --target install && \
  ldconfig && cd ${HOME} && rm -rf paho.mqtt.c && \
  git clone https://github.com/eclipse/paho.mqtt.cpp && cd paho.mqtt.cpp && \
  cmake -Bbuild -H. -DPAHO_BUILD_STATIC=ON -DPAHO_BUILD_DOCUMENTATION=TRUE -DPAHO_BUILD_SAMPLES=TRUE && \
  cmake --build build/ --target install && ldconfig && cd ${HOME} && rm -rf paho.mqtt.cpp

RUN update-alternatives --install /usr/bin/cc cc /usr/bin/clang 20 && \
    update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 20 && \
    update-alternatives --set cc /usr/bin/clang && \
    update-alternatives --set c++ /usr/bin/clang++

ENV PATH="/opt/toolchain/bin:${PATH}"

ADD ./entrypoint-nes-cross-build.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
