FROM ubuntu:20.04

COPY toolchain-aarch64-llvm.cmake toolchain-aarch64-llvm.cmake
RUN mkdir -p /opt/toolchain && \
cp toolchain-aarch64-llvm.cmake /opt/toolchain/toolchain-aarch64-llvm.cmake && \
apt-get update -qq && DEBIAN_FRONTEND="noninteractive" apt-get install --no-install-recommends -qq \
      build-essential \
      ca-certificates \
      crossbuild-essential-arm64 \
      libstdc++6-arm64-cross \
      g++-multilib \
      cmake \
      git \
      python3-dev \
      python-dev \
      libncurses5-dev \
      libxml2-dev \
      libedit-dev \
      swig \
      doxygen \
      graphviz \
      xz-utils \
      ninja-build \
      rsync \
      ssh \
      gdb \
      libssl-dev && \
    apt-get clean -qq

RUN sed -i -- 's|deb http|deb [arch=amd64] http|g' /etc/apt/sources.list && \
cp /etc/apt/sources.list /etc/apt/sources.list.d/ports.list && \
sed -i -- 's|amd64|arm64|g' /etc/apt/sources.list.d/ports.list && \
sed -i -E -- 's|http://.*archive\.ubuntu\.com/ubuntu|http://ports.ubuntu.com/ubuntu-ports|g' /etc/apt/sources.list.d/ports.list && \
sed -i -E -- 's|http://.*security\.ubuntu\.com/ubuntu|http://ports.ubuntu.com/ubuntu-ports|g' /etc/apt/sources.list.d/ports.list && \
dpkg --add-architecture arm64 && \
apt-get update

RUN apt-get install --no-install-recommends -o APT::Immediate-Configure=false -qq \
  libc++-dev:arm64 \
  libstdc++-9-dev:arm64 \
  libpython3-dev:arm64 \
  libncurses5-dev:arm64 \
  libxml2-dev:arm64 \
  libedit-dev:arm64 \
  libdwarf-dev:arm64 \
  libdw-dev:arm64 \
  liblog4cxx-dev:arm64 \
  libcpprest-dev:arm64 \
  libssl-dev:arm64 \
  libeigen3-dev:arm64 \
  libzmqpp-dev:arm64 \
  z3:arm64 \
  libz3-dev:arm64 && \
  apt-get clean -qq

RUN mkdir -p /opt/sysroots/aarch64-linux-gnu/usr && \
mkdir -p /opt/toolchain && \
cd /opt/sysroots/aarch64-linux-gnu/usr && \
cp -r -v -L /usr/aarch64-linux-gnu/include /usr/aarch64-linux-gnu/lib . && cd lib && \
cp -r -v -L /usr/lib/gcc-cross/aarch64-linux-gnu/9/*gcc* . && \
cp -r -v -L /usr/lib/gcc-cross/aarch64-linux-gnu/9/*crt* . && \
cp -r -v -L /usr/lib/gcc-cross/aarch64-linux-gnu/9/libsupc++.a . && \
cp -r -v -L /usr/lib/gcc-cross/aarch64-linux-gnu/9/libstdc++*  . && cd

RUN git config --global advice.detachedHead false && \
(git clone --quiet --single-branch --recursive https://github.com/boostorg/boost && cd boost && \
rm -rf more && git checkout boost-1.71.0 && ./bootstrap.sh && \
sed -i -- 's|using gcc ;|using gcc : arm64 : aarch64-linux-gnu-g++ ;|g' project-config.jam && \
./b2 install -j2 toolset=gcc-arm64 --prefix=/opt/sysroots/aarch64-linux-gnu/usr) || cd .. || rm -rf boost

RUN git clone --branch llvmorg-10.0.0 --single-branch https://github.com/llvm/llvm-project && \
mkdir -p llvm-project/build && cd llvm-project/build && \
cmake -G Ninja \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_INSTALL_PREFIX=/opt/toolchain \
-DCMAKE_CROSSCOMPILING=ON \
-DLLVM_BUILD_DOCS=OFF \
-DLLVM_DEFAULT_TARGET_TRIPLE=aarch64-linux-gnu \
-DLLVM_TARGET_ARCH=AArch64 \
-DLLVM_TARGETS_TO_BUILD=AArch64 \
-DLLVM_ENABLE_PROJECTS="clang;compiler-rt;lld;polly;libcxx;libcxxabi;openmp" \
../llvm && \
ninja -j 2 clang && ninja -j 2 cxx && ninja install && \
cd && rm -rf llvm-project

RUN cd && git clone --branch v1.28.1 https://github.com/grpc/grpc.git && \
cd grpc && git submodule update --init --recursive --jobs 1 && mkdir -p build && cd build && \
cmake .. -DCMAKE_BUILD_TYPE=Release -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF -DgRPC_SSL_PROVIDER=package && \
make -j2 install && cd .. && rm -rf build && mkdir -p build && cd build && \
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/opt/toolchain/toolchain-aarch64-llvm.cmake \
-DCMAKE_INSTALL_PREFIX=/opt/sysroots/aarch64-linux-gnu/ && \
make -j2 install && cd ../.. && rm -rf grpc

RUN cd /opt/sysroots/aarch64-linux-gnu/usr && \
cp -r -v -L /usr/aarch64-linux-gnu/include /usr/aarch64-linux-gnu/lib . && \
cp -r -v -L /usr/include/z3* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/zmq* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/log4* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/libdwarf* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/dwarf* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/elfutils* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/cpprest* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/pplx* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/aarch64-linux-gnu/openssl* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/openssl* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/aarch64-linux-gnu/c++/9* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/c++/9* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/gelf* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L cp -r -v -L /usr/include/libelf* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \
cp -r -v -L /usr/include/nlist* /opt/sysroots/aarch64-linux-gnu/usr/include/ && \

cp -r -v -L /usr/lib/aarch64-linux-gnu/libz3* /opt/sysroots/aarch64-linux-gnu/usr/lib/ && \
cp -r -v -L /usr/lib/aarch64-linux-gnu/libzmq* /opt/sysroots/aarch64-linux-gnu/usr/lib/ && \
cp -r -v -L /usr/lib/aarch64-linux-gnu/liblog4* /opt/sysroots/aarch64-linux-gnu/usr/lib/ && \
cp -r -v -L /usr/lib/aarch64-linux-gnu/libdwarf* /opt/sysroots/aarch64-linux-gnu/usr/lib/ && \
cp -r -v -L /usr/lib/aarch64-linux-gnu/libdw* /opt/sysroots/aarch64-linux-gnu/usr/lib/ && \
cp -r -v -L /usr/lib/aarch64-linux-gnu/libebl* /opt/sysroots/aarch64-linux-gnu/usr/lib/ && \
cp -r -v -L /usr/lib/aarch64-linux-gnu/libcpprest* /opt/sysroots/aarch64-linux-gnu/usr/lib/ && \
cp -r -v -L /usr/lib/aarch64-linux-gnu/cmake/cpprestsdk* /opt/sysroots/aarch64-linux-gnu/usr/lib/cmake/ && \
cp -r -v -L /usr/lib/aarch64-linux-gnu/libcrypto* /opt/sysroots/aarch64-linux-gnu/usr/lib/ && \
cp -r -v -L /usr/lib/aarch64-linux-gnu/libssl* /opt/sysroots/aarch64-linux-gnu/usr/lib/ && \
cp -r -v -L /usr/lib/aarch64-linux-gnu/libcpprest* /opt/sysroots/aarch64-linux-gnu/usr/lib/ && \
cp -r -v -L /usr/lib/llvm-10* /opt/sysroots/aarch64-linux-gnu/usr/lib/ && \
cp -r -v -L /usr/lib/gcc/aarch64-linux-gnu/9* /opt/sysroots/aarch64-linux-gnu/usr/lib/ && \
cp -r -v -L /usr/lib/aarch64-linux-gnu/libelf* /opt/sysroots/aarch64-linux-gnu/usr/lib/ && \
sed -i -- 's|/usr/lib/aarch64-linux-gnu/cmake/cpprestsdk|/opt/sysroots/aarch64-linux-gnu/usr/lib/cmake/cpprestsdk|g' /opt/sysroots/aarch64-linux-gnu/usr/lib/cmake/cpprestsdk/cpprestsdk-targets.cmake && \
sed -i -- 's|/lib/aarch64-linux-gnu/|/aarch64-linux-gnu/usr/lib/|g' /opt/sysroots/aarch64-linux-gnu/usr/lib/cmake/cpprestsdk/cpprestsdk-targets-none.cmake && \
sed -i -- 's|/include/|/aarch64-linux-gnu/usr/include/|g' /opt/sysroots/aarch64-linux-gnu/usr/lib/cmake/cpprestsdk/cpprestsdk-targets.cmake

RUN update-alternatives --install /usr/bin/clang clang /opt/toolchain/bin/clang 10 && \
    update-alternatives --install /usr/bin/clang++ clang++ /opt/toolchain/bin/clang++ 10 && \
    update-alternatives --install /usr/bin/cc cc /usr/bin/clang 20 && \
    update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 20 && \
    update-alternatives --set cc /usr/bin/clang && \
    update-alternatives --set c++ /usr/bin/clang++

ENV PATH="/opt/toolchain/bin:${PATH}"

RUN service ssh start && useradd -m nes && yes password | passwd nes

ADD ./entrypoint-nes-cross.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
