-- Test for fast starting and stopping of queries
CREATE LOGICAL SOURCE endless(ts UINT64);
CREATE PHYSICAL SOURCE FOR endless TYPE Generator SET(
       'ALL' as `SOURCE`.STOP_GENERATOR_WHEN_SEQUENCE_FINISHES,
       'CSV' as PARSER.`TYPE`,
       10000000 AS `SOURCE`.MAX_RUNTIME_MS,
       1 AS `SOURCE`.SEED,
       'SEQUENCE UINT64 0 10 1' AS `SOURCE`.GENERATOR_SCHEMA);
CREATE SINK someSink(ENDLESS.TS UINT64) TYPE File SET('WORKDIR/out.csv' as `SINK`.FILE_PATH, 'CSV' as `SINK`.INPUT_FORMAT);
SHOW QUERIES;
SELECT TS FROM ENDLESS INTO SOMESINK;

SHOW QUERIES WHERE id = 1;
DROP QUERY 1;

SHOW QUERIES;
