#ifndef NES_INCLUDE_MONITORING_PROTOCOLS_REPORTINGPROTOCOL_HPP_
#define NES_INCLUDE_MONITORING_PROTOCOLS_REPORTINGPROTOCOL_HPP_

namespace NES {

/**
 * @brief WIP
 */
class ReportingProtocol {

};

}

#endif //NES_INCLUDE_MONITORING_PROTOCOLS_REPORTINGPROTOCOL_HPP_
