FROM ubuntu:18.04

RUN apt-get update -y && apt-get install -y cmake clang \
    llvm-dev git libzmq3-dev libboost1.65-all-dev liblog4cxx-dev libcpprest-dev libssl-dev clang-format
RUN git clone https://github.com/actor-framework/actor-framework.git
RUN cd actor-framework && git checkout -b 0.17.3 && bash configure && cd build && make && make install
RUN apt-get remove -y git
RUN rm -rf actor-framework

VOLUME ["/iotdb"]

ADD ./scripts/entrypoint.sh /entrypoint.sh

EXPOSE 8081
EXPOSE 38938
ENTRYPOINT ["/entrypoint.sh"]
