FROM ubuntu:19.10

RUN apt-get update -qq && DEBIAN_FRONTEND="noninteractive" apt-get install -qq \
  libdwarf-dev \
  libdwarf1 \
  build-essential \
  cmake \
  clang \
  clang-format \
  git \
  g++ \
  gcc \
  gdb \
  htop \
  libboost-all-dev \
  libglib2.0-0 \
  libcpprest-dev \
  libdw-dev \
  liblog4cxx-dev \
  librdkafka1 \
  librdkafka++1 \
  librdkafka-dev \
  libssl-dev \
  libzmq3-dev \
  llvm-dev \
  python \
  rsync \
  tar \
  tmux \
  ssh \
  vim \
  wget \
&& apt-get clean -qq

RUN systemctl enable ssh && useradd -m nes && yes password | passwd nes

RUN git clone --single-branch --branch 0.17.3 https://github.com/actor-framework/actor-framework.git && \
    cd actor-framework && git checkout  && bash configure --libs-only && cd build && make -j3 && make install && \
    cd ${HOME} && git clone --single-branch --branch v0.3.1 https://github.com/mfontanini/cppkafka.git && \
    cd cppkafka && mkdir -p build && cd build && \
    cmake -DCPPKAFKA_BUILD_SHARED=ON -DCPPKAFKA_DISABLE_TESTS=ON -DCPPKAFKA_DISABLE_EXAMPLES=ON -DCPPKAFKA_RDKAFKA_STATIC_LIB=OFF .. && \
    make -j -w && make install && \
    apt-get remove -qq git wget && \
    cd ${HOME} && rm -rf actor-framework cppkafka*

ADD ./scripts/entrypoint-nes-build.sh /entrypoint-build.sh

EXPOSE 8081 38938
