FROM ubuntu:18.04

RUN apt-get update -y && apt-get remove -y llvm-6.0 && \
    apt-get install -y cmake clang-3.9 llvm-3.9-dev libclang-3.9-dev
RUN update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.9 100 && \
    update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.9 100
RUN apt-get install -y libzmq3-dev libboost1.65-all-dev liblog4cxx-dev libssl-dev libcpprest-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

VOLUME ["/iotdb"]

ADD ./scripts/entrypoint.sh /entrypoint.sh

EXPOSE 8081
EXPOSE 38938
ENTRYPOINT ["/entrypoint.sh"]
