FROM ubuntu:19.04

RUN apt-get update -qq && DEBIAN_FRONTEND="noninteractive" apt-get install -qq \
    binutils-dev \
    build-essential \
    cmake \
    clang \
    clang-format \
    git \
    g++ \
    gcc \
    libboost-all-dev \
    libglib2.0-0 \
    libcpprest-dev \
    libdw-dev \
    liblog4cxx-dev \
    librdkafka1 \
    librdkafka++1 \
    librdkafka-dev \
    libssl-dev \
    libzmq3-dev \
    llvm-dev \
    wget \
    ssh \
    build-essential \
    gcc \
    g++ \
    gdb \
    clang \
    cmake \
    rsync \
    tar \
    python \
&& apt-get clean 

RUN useradd -m nes && yes password | passwd nes

RUN git clone --single-branch --branch 0.17.3 https://github.com/actor-framework/actor-framework.git && \
    cd actor-framework && git checkout  && bash configure --libs-only && cd build && make -j3 && make install && \
    cd ${HOME} && git clone --single-branch --branch v0.3.1 https://github.com/mfontanini/cppkafka.git && \
    cd cppkafka && mkdir -p build && cd build && \
    cmake -DCPPKAFKA_BUILD_SHARED=ON -DCPPKAFKA_DISABLE_TESTS=ON -DCPPKAFKA_DISABLE_EXAMPLES=ON -DCPPKAFKA_RDKAFKA_STATIC_LIB=OFF .. && \
    make -j -w && make install && \
    apt-get remove -qq git wget && \
    cd ${HOME} && rm -rf actor-framework cppkafka*

EXPOSE 8081
EXPOSE 38938
