FROM nebulastream/nes-build-image:latest

RUN DEBIAN_FRONTEND="noninteractive" apt-get update -qq && apt-get install -qq \
  gdb \
  ninja-build \
&& apt-get clean -qq

ADD install-profiler.sh /install-profiler.sh
