---
name: 🌀 Enhancement
description: Suggest an enhancement
labels: ["enhancement"]
title: '[TASK]'
body:
  - type: markdown
    attributes:
      # yamllint disable rule:line-length
      value: "
        Thank you for finding the time to report the enhancement!
        
        We really appreciate the community's efforts to improve NebulaStream.
        <br clear='left'/>"
      # yamllint enable rule:line-length
  - type: textarea
    attributes:
      label: Description
      description: Description of the enhancement
    validations:
      required: true
  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: List of criteria to be meet
    validations:
      required: true
