FROM ubuntu:18.04

RUN apt-get update -qq && apt-get install -qq \
  clang \
  libdwarf-dev \
  libdwarf1 \
  llvm-dev \
  binutils-dev \
  libdw-dev \
  libboost-all-dev \
  liblog4cxx-dev \
  libcpprest-dev \
  libssl-dev \
  clang-format \
  librdkafka1 \
  librdkafka++1 \
  librdkafka-dev \
  git \
  wget \
  tar \
  && apt-get clean -qq

RUN wget https://github.com/Kitware/CMake/releases/download/v3.17.2/cmake-3.17.2.tar.gz && \
  tar -zxvf cmake-3.17.2.tar.gz && \
  cd cmake-3.17.2 && ./bootstrap && make -j3 && make install && \
  cd ${HOME} && rm -rf cmake-3.17.2 cmake-3.17.2.tar.gz && \
  cd ${HOME} && git clone --branch v1.28.1 https://github.com/grpc/grpc.git && \
  cd grpc && git submodule update --init --jobs 1 && mkdir -p build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release && \
  make -j2 && make install && cd ${HOME} && rm -rf grpc && \
  cd ${HOME} && git clone --single-branch --branch v0.3.1 https://github.com/mfontanini/cppkafka.git && \
  cd cppkafka && mkdir -p build && cd build && \
  cmake -DCPPKAFKA_BUILD_SHARED=ON -DCPPKAFKA_DISABLE_TESTS=ON -DCPPKAFKA_DISABLE_EXAMPLES=ON -DCPPKAFKA_RDKAFKA_STATIC_LIB=OFF .. && \
  make -j -w && make install && cd ${HOME} && rm -rf cppkafka* && \
  cd ${HOME} && git clone --single-branch --branch v4.3.2 https://github.com/zeromq/libzmq.git && cd libzmq && \
  mkdir -p build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release && make -j2 && make install && \
  cd ${HOME} && rm -rf libzmq && \
  cd ${HOME} && git clone --single-branch --branch v4.6.0 https://github.com/zeromq/cppzmq.git && cd cppzmq && \
  mkdir -p build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release && make -j2 && make install && \
  cd ${HOME} && rm -rf cppzmq && \
  apt-get purge -y wget && apt autoremove -y

ADD ./scripts/entrypoint-nes-build.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

