FROM nebulastream/nes-build-image:latest AS buildimg

COPY ./ /nebulastream

RUN mkdir -p /nebulastream/build && \
    cd /nebulastream/build && \
    cmake -DCMAKE_BUILD_TYPE=Release -DNES_SELF_HOSTING=1 -DNES_USE_OPC=0 -DNES_USE_MQTT=1 -DNES_USE_ADAPTIVE=0 .. && \
    make version && make -j4 && cpack && mv *.deb /nes.deb && \
    rm -rf /nebulastream/build/nes-dependencies-v14-x64-linux-nes.7z


FROM ubuntu:20.04 AS execimg

COPY --from=buildimg /nes.deb .
COPY --from=buildimg /nebulastream/build/nes-dependencies-v14-x64-linux-nes/installed/x64-linux-nes/ /nebulastream/build/nes-dependencies-v14-x64-linux-nes/installed/x64-linux-nes/
COPY ./docker/executableImage/resources/exdra.csv /opt/local/nebula-stream/exdra.csv
COPY ./docker/executableImage/entrypoint-nes-executable.sh /entrypoint.sh

ENV coordinatorCLIConf="--coordinatorIp=127.0.0.1 --rpcPort=12346 --restIp=0.0.0.0 --restPort=8081 --logLevel=LOG_INFO"
ENV workerCLIConf="--coordinatorPort=12346 --logLevel=LOG_INFO --physicalSources.type=CSVSource --physicalSources.filePath=/opt/local/nebula-stream/exdra.csv --physicalSources.numberOfBuffersToProduce=100 --physicalSources.sourceFrequency=1 --physicalSources.physicalSourceName=exdra_worker_1 --physicalSources.logicalSourceName=exdra --physicalSources.skipHeader=false --physicalSources.delimiter=,"

RUN apt update && apt install --no-install-recommends -y -qq \
    software-properties-common \
    libdwarf-dev \
    libdwarf1 \
    binutils-dev \
    libdw-dev \
    libssl-dev \
    wget \
    && cd ${HOME} && wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null \
    && apt-add-repository 'deb https://apt.kitware.com/ubuntu/ focal main' \
    && apt install --no-install-recommends -y -qq kitware-archive-keyring && rm /etc/apt/trusted.gpg.d/kitware.gpg && apt update && apt install --no-install-recommends -y cmake \
    && dpkg -i /nes.deb && rm -rf /*.deb \
    && apt purge software-properties-common wget kitware-archive-keyring -y \
    && apt autoclean -y && apt autoremove -y \
    && rm -rf /var/cache/apt/archives* \
    && rm -rf /var/lib/apt/lists/*


ENTRYPOINT ["/entrypoint.sh"]