FROM nebulastream/nes-build-image:latest AS buildimg

COPY ./ /nebulastream

RUN mkdir -p /nebulastream/build && \
    cd /nebulastream/build && \
    cmake -DCMAKE_BUILD_TYPE=Release -DNES_SELF_HOSTING=1 -DNES_USE_OPC=0 -DNES_USE_MQTT=1 -DNES_USE_ADAPTIVE=0 .. && \
    make version && make -j4 && cpack && mv *.deb /nes.deb && \
    rm -rf /nebulastream/build/nes-dependencies-v13-x64-linux-nes.7z

FROM nebulastream/nes-build-image:latest AS execimg

COPY --from=buildimg /nes.deb .
COPY --from=buildimg /nebulastream/build/nes-dependencies-v13-x64-linux-nes/installed/x64-linux-nes/ /nebulastream/build/nes-dependencies-v13-x64-linux-nes/installed/x64-linux-nes/

RUN dpkg -i /nes.deb && apt install iproute2 ifupdown net-tools --no-install-recommends -y -qq && \
apt autoclean -y -qq && rm -rf /*.deb

COPY ./docker/executableImage/resources/exdra.csv /opt/local/nebula-stream/exdra.csv
COPY ./docker/executableImage/entrypoint-prepare-nes-package.sh /entrypoint-prepare-nes-package.sh
COPY ./docker/executableImage/entrypoint-containernet.sh /entrypoint-containernet.sh
COPY ./docker/executableImage/entrypoint-nes-executable.sh /entrypoint.sh

ENV restIp="0.0.0.0"
ENV restPort=8081
ENV coordinatorIp="127.0.0.1"
ENV coordinatorPort="12346"
ENV enableSemanticQueryValidation=false
ENV sourceType="CSVSource"
ENV mqttSourceType="/opt/local/nebula-stream/exdra.csv"
ENV numberOfBuffersToProduce=100
ENV sourceFrequency=1
ENV physicalSourceName="exdra_worker_1"
ENV logicalSourceName="exdra"
ENV skipHeader=false

ENTRYPOINT ["/entrypoint.sh"]
