FROM nebulastream/nes-build-image:latest

ADD ./resources/*.deb *.deb
RUN dpkg -i *.deb
ADD ./resources/exdra.csv /opt/local/nebula-stream/exdra.csv
ADD ./entrypoint-nes-executable.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
