FROM ubuntu:22.04 AS execimg
ARG TARGETARCH
COPY ./nes-$TARGETARCH.deb nes.deb

RUN apt-get update -qq && DEBIAN_FRONTEND="noninteractive" apt-get install -qq  \
    libstdc++-11-dev \
    libobjc-11-dev \
    libstdc++6  \
    libgcc-s1 \
    libc6  \
    libc6-dev \
    binutils  \
    libnuma-dev  \
    libdwarf-dev  \
    libdwarf1 \
    libomp-12-dev \
    binutils-dev \
    libunwind-dev  \
    libdw-dev iproute2  \
    ifupdown  \
    openjdk-17-jre \
    libopencv4.5-java \
    libopencv4.5d-jni \
    net-tools --no-install-recommends -y -qq && DEBIAN_FRONTEND="noninteractive" apt install -y -qq  ./nes.deb &&  rm nes.deb

COPY ./docker/executableImage/entrypoint-nes-executable.sh /entrypoint.sh

ENV coordinatorCLIConf="--coordinatorIp=127.0.0.1 --rpcPort=12346 --restIp=0.0.0.0 --restPort=8081 --logLevel=LOG_INFO"
ENV workerCLIConf="--coordinatorPort=12346 --logLevel=LOG_INFO"

ENTRYPOINT ["/entrypoint.sh"]
