SELECT
  "ts",
  "slot",
  "p_absent"
FROM
(
  SELECT
    "ts",
    VARSIZED('A1') AS "slot",
    "p_absent"
  FROM
    MODEL_INFERENCE(BUCKET_SLOT_CNN,
      (SELECT
         CASTTOUNIXTS("ts") AS "ts",
         FT_PREPROCESS_SLOT("data", CASTTOTYPE(86 AS UINT32), CASTTOTYPE(10 AS UINT32), CASTTOTYPE(55 AS UINT32), CASTTOTYPE(51 AS UINT32)) AS "pixels"
       FROM SSC_CAM_A1))
  UNION
  SELECT
    "ts",
    VARSIZED('A2') AS "slot",
    "p_absent"
  FROM
    MODEL_INFERENCE(BUCKET_SLOT_CNN,
      (SELECT
         CASTTOUNIXTS("ts") AS "ts",
         FT_PREPROCESS_SLOT("data", CASTTOTYPE(155 AS UINT32), CASTTOTYPE(20 AS UINT32), CASTTOTYPE(57 AS UINT32), CASTTOTYPE(50 AS UINT32)) AS "pixels"
       FROM SSC_CAM_A2))
  UNION
  SELECT
    "ts",
    VARSIZED('A3') AS "slot",
    "p_absent"
  FROM
    MODEL_INFERENCE(BUCKET_SLOT_CNN,
      (SELECT
         CASTTOUNIXTS("ts") AS "ts",
         FT_PREPROCESS_SLOT("data", CASTTOTYPE(240 AS UINT32), CASTTOTYPE(30 AS UINT32), CASTTOTYPE(76 AS UINT32), CASTTOTYPE(55 AS UINT32)) AS "pixels"
       FROM SSC_CAM_A3))
  UNION
  SELECT
    "ts",
    VARSIZED('B1') AS "slot",
    "p_absent"
  FROM
    MODEL_INFERENCE(BUCKET_SLOT_CNN,
      (SELECT
         CASTTOUNIXTS("ts") AS "ts",
         FT_PREPROCESS_SLOT("data", CASTTOTYPE(88 AS UINT32), CASTTOTYPE(63 AS UINT32), CASTTOTYPE(56 AS UINT32), CASTTOTYPE(40 AS UINT32)) AS "pixels"
       FROM SSC_CAM_B1))
  UNION
  SELECT
    "ts",
    VARSIZED('B2') AS "slot",
    "p_absent"
  FROM
    MODEL_INFERENCE(BUCKET_SLOT_CNN,
      (SELECT
         CASTTOUNIXTS("ts") AS "ts",
         FT_PREPROCESS_SLOT("data", CASTTOTYPE(149 AS UINT32), CASTTOTYPE(73 AS UINT32), CASTTOTYPE(69 AS UINT32), CASTTOTYPE(52 AS UINT32)) AS "pixels"
       FROM SSC_CAM_B2))
  UNION
  SELECT
    "ts",
    VARSIZED('B3') AS "slot",
    "p_absent"
  FROM
    MODEL_INFERENCE(BUCKET_SLOT_CNN,
      (SELECT
         CASTTOUNIXTS("ts") AS "ts",
         FT_PREPROCESS_SLOT("data", CASTTOTYPE(237 AS UINT32), CASTTOTYPE(88 AS UINT32), CASTTOTYPE(78 AS UINT32), CASTTOTYPE(62 AS UINT32)) AS "pixels"
       FROM SSC_CAM_B3))
  UNION
  SELECT
    "ts",
    VARSIZED('C1') AS "slot",
    "p_absent"
  FROM
    MODEL_INFERENCE(BUCKET_SLOT_CNN,
      (SELECT
         CASTTOUNIXTS("ts") AS "ts",
         FT_PREPROCESS_SLOT("data", CASTTOTYPE(92 AS UINT32), CASTTOTYPE(107 AS UINT32), CASTTOTYPE(51 AS UINT32), CASTTOTYPE(51 AS UINT32)) AS "pixels"
       FROM SSC_CAM_C1))
  UNION
  SELECT
    "ts",
    VARSIZED('C2') AS "slot",
    "p_absent"
  FROM
    MODEL_INFERENCE(BUCKET_SLOT_CNN,
      (SELECT
         CASTTOUNIXTS("ts") AS "ts",
         FT_PREPROCESS_SLOT("data", CASTTOTYPE(150 AS UINT32), CASTTOTYPE(128 AS UINT32), CASTTOTYPE(72 AS UINT32), CASTTOTYPE(50 AS UINT32)) AS "pixels"
       FROM SSC_CAM_C2))
  UNION
  SELECT
    "ts",
    VARSIZED('C3') AS "slot",
    "p_absent"
  FROM
    MODEL_INFERENCE(BUCKET_SLOT_CNN,
      (SELECT
         CASTTOUNIXTS("ts") AS "ts",
         FT_PREPROCESS_SLOT("data", CASTTOTYPE(226 AS UINT32), CASTTOTYPE(153 AS UINT32), CASTTOTYPE(88 AS UINT32), CASTTOTYPE(53 AS UINT32)) AS "pixels"
       FROM SSC_CAM_C3))
)
WHERE
  FT_LOG_SCORE("ts", "slot", "p_absent") > FLOAT32(0.85)
INTO
  SSC_SLOT_ANOMALY_SINK
;
