SELECT
  "ts",
  "slot",
  "p_absent"
FROM
(
  SELECT
    "ts",
    VARSIZED('A1') AS "slot",
    "p_absent"
  FROM
    MODEL_INFERENCE(BUCKET_SLOT_CNN,
      (SELECT
         CASTTOUNIXTS("ts") AS "ts",
         FT_PREPROCESS_SLOT("data", CASTTOTYPE(80 AS UINT32), CASTTOTYPE(14 AS UINT32), CASTTOTYPE(60 AS UINT32), CASTTOTYPE(39 AS UINT32)) AS "pixels"
       FROM SSC_CAM_A1))
  UNION
  SELECT
    "ts",
    VARSIZED('A2') AS "slot",
    "p_absent"
  FROM
    MODEL_INFERENCE(BUCKET_SLOT_CNN,
      (SELECT
         CASTTOUNIXTS("ts") AS "ts",
         FT_PREPROCESS_SLOT("data", CASTTOTYPE(150 AS UINT32), CASTTOTYPE(19 AS UINT32), CASTTOTYPE(64 AS UINT32), CASTTOTYPE(45 AS UINT32)) AS "pixels"
       FROM SSC_CAM_A2))
  UNION
  SELECT
    "ts",
    VARSIZED('A3') AS "slot",
    "p_absent"
  FROM
    MODEL_INFERENCE(BUCKET_SLOT_CNN,
      (SELECT
         CASTTOUNIXTS("ts") AS "ts",
         FT_PREPROCESS_SLOT("data", CASTTOTYPE(245 AS UINT32), CASTTOTYPE(31 AS UINT32), CASTTOTYPE(67 AS UINT32), CASTTOTYPE(52 AS UINT32)) AS "pixels"
       FROM SSC_CAM_A3))
  UNION
  SELECT
    "ts",
    VARSIZED('B1') AS "slot",
    "p_absent"
  FROM
    MODEL_INFERENCE(BUCKET_SLOT_CNN,
      (SELECT
         CASTTOUNIXTS("ts") AS "ts",
         FT_PREPROCESS_SLOT("data", CASTTOTYPE(92 AS UINT32), CASTTOTYPE(68 AS UINT32), CASTTOTYPE(42 AS UINT32), CASTTOTYPE(32 AS UINT32)) AS "pixels"
       FROM SSC_CAM_B1))
  UNION
  SELECT
    "ts",
    VARSIZED('B2') AS "slot",
    "p_absent"
  FROM
    MODEL_INFERENCE(BUCKET_SLOT_CNN,
      (SELECT
         CASTTOUNIXTS("ts") AS "ts",
         FT_PREPROCESS_SLOT("data", CASTTOTYPE(156 AS UINT32), CASTTOTYPE(76 AS UINT32), CASTTOTYPE(58 AS UINT32), CASTTOTYPE(41 AS UINT32)) AS "pixels"
       FROM SSC_CAM_B2))
  UNION
  SELECT
    "ts",
    VARSIZED('B3') AS "slot",
    "p_absent"
  FROM
    MODEL_INFERENCE(BUCKET_SLOT_CNN,
      (SELECT
         CASTTOUNIXTS("ts") AS "ts",
         FT_PREPROCESS_SLOT("data", CASTTOTYPE(252 AS UINT32), CASTTOTYPE(97 AS UINT32), CASTTOTYPE(55 AS UINT32), CASTTOTYPE(44 AS UINT32)) AS "pixels"
       FROM SSC_CAM_B3))
  UNION
  SELECT
    "ts",
    VARSIZED('C1') AS "slot",
    "p_absent"
  FROM
    MODEL_INFERENCE(BUCKET_SLOT_CNN,
      (SELECT
         CASTTOUNIXTS("ts") AS "ts",
         FT_PREPROCESS_SLOT("data", CASTTOTYPE(99 AS UINT32), CASTTOTYPE(114 AS UINT32), CASTTOTYPE(44 AS UINT32), CASTTOTYPE(33 AS UINT32)) AS "pixels"
       FROM SSC_CAM_C1))
  UNION
  SELECT
    "ts",
    VARSIZED('C2') AS "slot",
    "p_absent"
  FROM
    MODEL_INFERENCE(BUCKET_SLOT_CNN,
      (SELECT
         CASTTOUNIXTS("ts") AS "ts",
         FT_PREPROCESS_SLOT("data", CASTTOTYPE(166 AS UINT32), CASTTOTYPE(134 AS UINT32), CASTTOTYPE(45 AS UINT32), CASTTOTYPE(39 AS UINT32)) AS "pixels"
       FROM SSC_CAM_C2))
  UNION
  SELECT
    "ts",
    VARSIZED('C3') AS "slot",
    "p_absent"
  FROM
    MODEL_INFERENCE(BUCKET_SLOT_CNN,
      (SELECT
         CASTTOUNIXTS("ts") AS "ts",
         FT_PREPROCESS_SLOT("data", CASTTOTYPE(235 AS UINT32), CASTTOTYPE(155 AS UINT32), CASTTOTYPE(68 AS UINT32), CASTTOTYPE(52 AS UINT32)) AS "pixels"
       FROM SSC_CAM_C3))
)
WHERE
  FT_LOG_SCORE("ts", "slot", "p_absent") > FLOAT32(0.5)
INTO
  SSC_SLOT_ANOMALY_SINK
;
