SELECT
  "ts",
  VARSIZED('B2') AS "slot",
  "p_absent"
FROM
  MODEL_INFERENCE(BUCKET_SLOT_CNN,
    (SELECT
       CASTTOUNIXTS("ts") AS "ts",
       FT_PREPROCESS_SLOT("data", CASTTOTYPE(149 AS UINT32), CASTTOTYPE(73 AS UINT32), CASTTOTYPE(69 AS UINT32), CASTTOTYPE(52 AS UINT32)) AS "pixels"
     FROM SSC_CAM))
WHERE
  FT_LOG_SCORE("ts", VARSIZED('B2'), "p_absent") > FLOAT32(0.85)
INTO
  SSC_SLOT_ANOMALY_DEBUG_SINK
;
