SELECT
  "ts",
  VARSIZED('B2') AS "slot",
  "p_absent"
FROM
  MODEL_INFERENCE(BUCKET_SLOT_CNN,
    (SELECT
       CASTTOUNIXTS("ts") AS "ts",
       FT_PREPROCESS_SLOT("data", CASTTOTYPE(156 AS UINT32), CASTTOTYPE(76 AS UINT32), CASTTOTYPE(58 AS UINT32), CASTTOTYPE(41 AS UINT32)) AS "pixels"
     FROM SSC_CAM))
WHERE
  FT_LOG_SCORE("ts", VARSIZED('B2'), "p_absent") > FLOAT32(0.5)
INTO
  SSC_SLOT_ANOMALY_DEBUG_SINK
;
