name: Prepare GitHub CI Server Instance
description: |
  Prepares a github ci server instance by removing unnecessary pre-installed software pulling the docker image and 
  preparing ccache.

inputs:
  ccache_key:
    description: 'key of the ccache github cache'
    required: true
  image_name:
    description: 'name of the docker image to prepare'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Maximize build space
      # Idea was taken from https://github.com/marketplace/actions/maximize-build-disk-space. GitHub hosted ci servers
      # have around 100 gb of diskspace, however, alot is already claimed by pre-installed software.
      # Because this is actually removing alot of files which so we overlap it with installing dependencies and fetching
      # the docker image
      shell: bash
      run: |
        $(which sudo) apt-get install -y ccache &
        docker pull ${{inputs.image_name}} &
        
        df -h
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        df -h
        wait
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2.18
      with:
        key: ${{inputs.ccache_key}}
