#!/usr/bin/env python3

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    https://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Phase-0 producer-bottleneck experiment (see producer-bottleneck-findings.md).

Hypothesis: the parser plateaus at ~6 worker threads because a SINGLE producer
(one reader thread per source) cannot fill the task queue fast enough. To test
it without engine changes, we split the 5 GB CSV into N line-aligned slices,
declare N File sources, UNION them, and project `key` into a Void sink under the
NES_DISABLE_EMIT gate -- giving N independent producer threads over a fixed 5 GB
of input.

CRITICAL: `TYPE File` is the async FileSource, and the async IOThread pool
round-robins sources across `number_of_io_threads` io_contexts. So N sources only
become N producer threads when number_of_io_threads >= N. This runner sets
number_of_io_threads = N for every N-source run (N=1 reproduces the baseline).

If the throughput knee moves up with N (mirroring the sleepy-PoC P=1 -> P=2
result), single-producer starvation is confirmed as the cause.

Usage (from repo root):
  # prepare only (slice + write the .test files, no benchmark run):
  python3 scripts/benchmarking/run_union_bench.py --gen-only
  # full sweep:
  python3 scripts/benchmarking/run_union_bench.py --reps 5 --producers 1 2 4 6 --threads 1 2 3 4 5 6 7 8 10 12 14
"""
from __future__ import annotations

import argparse
import json
import os
import statistics
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from slice_csv import slice_file  # noqa: E402

REPO = Path(__file__).resolve().parents[2]
HELPER = REPO / ".claude/skills/nes-build/in-docker.sh"
BUILD_DIR = "cmake-build-release-piparse"
DATA_DIR = REPO / "nes-systests/testdata"
# Base 5 GB CSV (5 x UINT64), relative to DATA_DIR, and where slices live.
BASE_REL = "large/formatter/bench_5xUINT64_5g.csv"
SLICE_ROOT_REL = "large/formatter/slices"
TEST_DIR = REPO / "nes-systests/benchmark"
WORKDIR_TOKEN = "{build}/fmt-bench-wd"
RESULTS_JSON = REPO / BUILD_DIR / "fmt-bench-wd" / "BenchmarkResults.json"
OPERATOR_BUFFER_SIZE = 128 * 1024
GLOBAL_BUFFERS = 65536
# fnattr invoke-mode: stamps the parse proxy-calls readonly/willreturn/nounwind so LLVM DCEs the
# parses for unprojected fields. OFF by default => up to 5x parse work. {repo} is substituted by
# the in-docker.sh helper. Without this the optimized config is NOT active (see the cheatsheet).
FNATTR_YAML = "{repo}/testing/configurations/invokeModeConfGlobalFnAttr.yaml"
SCHEMA = "creationTS UINT64 NOT NULL, key UINT64 NOT NULL, v1 UINT64 NOT NULL, v2 UINT64 NOT NULL, v3 UINT64 NOT NULL"


def set_clause(parser: str) -> str:
    """The INPUT_FORMATTER SET clause: SIMDCSV flat-band indexer + an optional UINT64 parser override
    (e.g. TracedUINT64 / FastUINT64). `parser == "none"` keeps the default (alloc-free) parser."""
    parts = ['"SIMDCSV" AS INPUT_FORMATTER.`TYPE`']
    if parser != "none":
        parts.append(f'"{parser}" AS INPUT_FORMATTER.`UINT64_PARSER`')
    return "SET(" + ", ".join(parts) + ")"


def source_rel_paths(n: int) -> list[str]:
    """Relative-to-DATA_DIR paths for the N input files (the original for N=1, else slices)."""
    if n == 1:
        return [BASE_REL]
    out_dir = DATA_DIR / SLICE_ROOT_REL / f"n{n}"
    paths = slice_file(DATA_DIR / BASE_REL, n, out_dir)
    return [str(p.relative_to(DATA_DIR)) for p in paths]


def gen_test(n: int, parser: str) -> Path:
    """Write FormatterUnion_N{n}.test (N File sources -> UNION -> SELECT key -> Void) and return its path."""
    rels = source_rel_paths(n)
    clause = set_clause(parser)
    lines = [
        f"# name: benchmark/FormatterUnion_N{n}.test",
        f"# description: Phase-0 producer-bottleneck probe. {n} File source(s) UNION'd, projecting key",
        "#              into a Void sink, run under NES_DISABLE_EMIT with number_of_io_threads=N so each",
        "#              source gets its own producer thread. GENERATED by run_union_bench.py.",
        f"#              Formatter: {clause}",
        "# groups: [Formatter, benchmark, large]",
        "",
    ]
    for i, rel in enumerate(rels, start=1):
        lines += [
            f"CREATE LOGICAL SOURCE s{i}({SCHEMA});",
            f"CREATE PHYSICAL SOURCE FOR s{i} TYPE File {clause};",
            f"ATTACH FILE {rel}",
            "",
        ]
    # UNION (n>=2) strips the source qualifier => the sink column is the bare `key`. A single source
    # (n==1, the 1-producer baseline) keeps the `s1.`-qualifier, so the sink must match it or binding fails.
    sink_col = "key" if n >= 2 else "s1.key"
    lines += [f"CREATE SINK u_void({sink_col} UINT64 NOT NULL) TYPE Void;", ""]
    arms = "\nUNION\n".join(f"SELECT key FROM s{i}" for i in range(1, n + 1))
    lines += [f"{arms}", "INTO u_void;", "----", ""]  # empty expected result (Void + no-emit)

    test_path = TEST_DIR / f"FormatterUnion_N{n}.test"
    test_path.write_text("\n".join(lines))
    return test_path


def run_one(test_path: Path, threads: int, io_threads: int) -> tuple[float, float] | None:
    """Run the union query once; return (GB/s, seconds) or None on failure."""
    if RESULTS_JSON.exists():
        RESULTS_JSON.unlink()
    test_token = "{repo}/" + str(test_path.relative_to(REPO))
    cmd = [
        str(HELPER),
        "env", "NES_DISABLE_EMIT=1",
        "{build}/nes-systests/systest/systest",
        "-t", f"{test_token}:1",
        "--data", "{repo}/nes-systests/testdata",
        "--workingDir", WORKDIR_TOKEN,
        "-b", "--",
        f"--worker.query_engine.number_of_worker_threads={threads}",
        f"--worker.query_engine.number_of_io_threads={io_threads}",
        f"--worker.default_query_execution.operator_buffer_size={OPERATOR_BUFFER_SIZE}",
        f"--worker.number_of_buffers_in_global_buffer_manager={GLOBAL_BUFFERS}",
        f"--worker.query_engine.invoke_mode_configuration={FNATTR_YAML}",
    ]
    env = {**os.environ, "NES_BUILD_DIR": BUILD_DIR}
    subprocess.run(cmd, env=env, cwd=REPO, capture_output=True, text=True)
    if not RESULTS_JSON.exists():
        return None
    try:
        data = json.loads(RESULTS_JSON.read_text())
    except json.JSONDecodeError:
        return None
    if not isinstance(data, list) or len(data) != 1:
        return None
    bps, secs = data[0]["bytesPerSecond"], data[0]["time"]
    if not (bps and bps == bps and bps > 0):
        return None
    return bps / 1e9, secs


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--reps", type=int, default=5)
    ap.add_argument("--producers", type=int, nargs="+", default=[1, 2, 4, 6])
    ap.add_argument("--threads", type=int, nargs="+", default=[1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 14])
    ap.add_argument("--warmup", type=int, default=1)
    ap.add_argument("--parser", default="TracedUINT64",
                    help="UINT64 parser override (TracedUINT64=new default, FastUINT64, none=alloc-free builtin)")
    ap.add_argument("--gen-only", action="store_true", help="slice + write .test files, do not run the benchmark")
    args = ap.parse_args()

    # Prepare slices + generated .test files for every producer count.
    print(f"[config] {set_clause(args.parser)} + fnattr + {OPERATOR_BUFFER_SIZE // 1024} KiB buffers "
          f"+ {GLOBAL_BUFFERS} global buffers, NES_DISABLE_EMIT=1, io_threads=N", flush=True)
    tests = {n: gen_test(n, args.parser) for n in args.producers}
    for n, p in tests.items():
        print(f"[prepared] N={n}: {p.relative_to(REPO)}  ({len(source_rel_paths(n))} source(s))", flush=True)
    if args.gen_only:
        print("\n--gen-only: slices + .test files ready; skipping benchmark run.")
        return

    # gbps[threads][n] = median GB/s
    gbps: dict[int, dict[int, float | None]] = {t: {} for t in args.threads}
    for n in args.producers:
        for threads in args.threads:
            samples: list[float] = []
            for rep in range(args.reps + args.warmup):
                res = run_one(tests[n], threads, io_threads=n)
                if rep >= args.warmup and res is not None:
                    samples.append(res[0])
                tag = "warmup" if rep < args.warmup else f"rep{rep - args.warmup + 1}"
                shown = f"{res[0]:.2f} GB/s ({res[1]:.2f}s)" if res else "FAILED"
                print(f"  [N={n} threads={threads}] {tag}: {shown}", flush=True)
            gbps[threads][n] = statistics.median(samples) if samples else None

    # Combined knee table: rows = worker threads, cols = producer count, cells = GB/s.
    print("\n## throughput GB/s  (rows = worker threads, cols = producers N)\n")
    header = "| threads | " + " | ".join(f"N={n}" for n in args.producers) + " |"
    print(header)
    print("|" + "---|" * (len(args.producers) + 1))
    for t in args.threads:
        cells = []
        for n in args.producers:
            v = gbps[t][n]
            cells.append(f"{v:.2f}" if v is not None else "fail")
        print(f"| {t:7} | " + " | ".join(cells) + " |")
    print("\nKnee check: if the N>1 columns keep climbing past where N=1 flattens (~6 threads),")
    print("single-producer starvation is confirmed.")


if __name__ == "__main__":
    main()
