CREATE LOGICAL SOURCE endless(val_1 UINT32, ts UINT64);
CREATE PHYSICAL SOURCE FOR endless TYPE Generator SET(
    'ALL' as `SOURCE`.STOP_GENERATOR_WHEN_SEQUENCE_FINISHES,
    'CSV' as PARSER.`TYPE`,
    10000000 as `SOURCE`.MAX_RUNTIME_MS,
    'SEQUENCE UINT32 0 10000000 1, SEQUENCE UINT64 0 10000000 1' AS `SOURCE`.GENERATOR_SCHEMA);
SELECT TS FROM ENDLESS INTO Void() SET (1 AS `QUERY`.`ID`);
SELECT * FROM ENDLESS INTO Void() SET (2 AS `QUERY`.`ID`);
SHOW QUERIES;
DROP QUERY ALL;
SHOW QUERIES;
