-- Read a PyArrow-generated Arrow IPC file through ArrowFileSource and write back as Arrow IPC.
-- ARROW_INPUT_PATH and ARROW_OUTPUT_PATH are substituted by the test harness.
-- Schema must match generate_arrow_testdata.py exactly.
CREATE LOGICAL SOURCE pydata(
    id UINT64 NOT NULL,
    vi8 INT8 NOT NULL,
    vi16 INT16 NOT NULL,
    vi32 INT32 NOT NULL,
    vi64 INT64 NOT NULL,
    vu8 UINT8 NOT NULL,
    vu16 UINT16 NOT NULL,
    vu32 UINT32 NOT NULL,
    vu64 UINT64 NOT NULL,
    vf32 FLOAT32 NOT NULL,
    vf64 FLOAT64 NOT NULL,
    vbool BOOLEAN NOT NULL,
    ni32 INT32,
    nf64 FLOAT64);
CREATE PHYSICAL SOURCE FOR pydata TYPE ArrowFile SET(
       'ARROW_INPUT_PATH' AS `SOURCE`.FILE_PATH,
       'ARROW' AS PARSER.`TYPE`);
CREATE SINK arrow_out(
    PYDATA.ID UINT64 NOT NULL,
    PYDATA.VI8 INT8 NOT NULL,
    PYDATA.VI16 INT16 NOT NULL,
    PYDATA.VI32 INT32 NOT NULL,
    PYDATA.VI64 INT64 NOT NULL,
    PYDATA.VU8 UINT8 NOT NULL,
    PYDATA.VU16 UINT16 NOT NULL,
    PYDATA.VU32 UINT32 NOT NULL,
    PYDATA.VU64 UINT64 NOT NULL,
    PYDATA.VF32 FLOAT32 NOT NULL,
    PYDATA.VF64 FLOAT64 NOT NULL,
    PYDATA.VBOOL BOOLEAN NOT NULL,
    PYDATA.NI32 INT32,
    PYDATA.NF64 FLOAT64) TYPE ArrowFile SET(
       'ARROW_OUTPUT_PATH' AS `SINK`.FILE_PATH);
SELECT ID, VI8, VI16, VI32, VI64, VU8, VU16, VU32, VU64, VF32, VF64, VBOOL, NI32, NF64
FROM PYDATA INTO ARROW_OUT SET ('pyarrow-interop' AS `QUERY`.`ID`);
