# Topology:
#
#   ┌──────────────────────────┐     ┌──────────────────────────┐
#   │ source-node:8080 (S)(K)  │────►│ sink-node:8080 (K)       │
#   │ capacity: 2              │     │ capacity: 10000          │
#   └──────────────────────────┘     └──────────────────────────┘
#
workers:
  - host: "sink-node:8080"
    data_address: "sink-node:9090"
    max_operators: 10000
    config:
      worker:
        query_engine:
          number_of_worker_threads: 1
  - host: "source-node:8080"
    data_address: "source-node:9090"
    max_operators: 2
    downstream:
      - "sink-node:8080"
    config:
      worker:
        query_engine:
          number_of_worker_threads: 1

allow_source_placement:
  - "source-node:8080"

allow_sink_placement:
  - "sink-node:8080"
  - "source-node:8080"
