FROM nebulastream/nes-executable-image:latest

RUN apt-get install iputils-ping -y
RUN apt-get install prometheus-node-exporter -y

RUN mkdir -p /logs

EXPOSE 9100 3000 3001

COPY entrypoint-prom.sh ./entrypoint-prom.sh