FROM ubuntu:20.04

RUN apt-get update -qq && DEBIAN_FRONTEND="noninteractive" apt-get install -qq \
  clang \
  cmake \
  libdwarf-dev \
  libdwarf1 \
  llvm-dev \
  binutils-dev \
  libdw-dev \
  libboost-all-dev \
  liblog4cxx-dev \
  libcpprest-dev \
  libssl-dev \
  clang-format \
  librdkafka1 \
  librdkafka++1 \
  librdkafka-dev \
  libzmqpp-dev \
  git \
  wget \
  tar \
  && apt-get clean -qq

RUN apt-get install -y software-properties-common -qq && \
  add-apt-repository ppa:open62541-team/ppa && \
  apt-get update -qq && \
  apt-get install libopen62541-1-dev -qq \
  && apt-get clean -qq

RUN cd ${HOME} && git clone --branch v1.28.1 https://github.com/grpc/grpc.git && \
  cd grpc && git submodule update --init --jobs 1 && mkdir -p build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release && \
  make -j && make install && cd ${HOME} && rm -rf grpc && \
  cd ${HOME} && git clone --single-branch --branch v0.3.1 https://github.com/mfontanini/cppkafka.git && \
  cd cppkafka && mkdir -p build && cd build && \
  cmake -DCPPKAFKA_BUILD_SHARED=ON -DCPPKAFKA_DISABLE_TESTS=ON -DCPPKAFKA_DISABLE_EXAMPLES=ON -DCPPKAFKA_RDKAFKA_STATIC_LIB=OFF .. && \
  make -j -w && make install && cd ${HOME} && rm -rf cppkafka* && \
  apt-get purge -y wget && apt autoremove -y

ADD ./entrypoint-nes-build.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
