FROM alpine:3.15

RUN apk add --no-cache --no-progress -q cmake --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community \
&& apk add --no-cache --no-progress -q \
    g++ \
    gcc-objc \
    libstdc++6 \
    libgcc \
    libc6-compat \
    musl \
    musl-dev \
    libnuma-dev \
    binutils \
    binutils-dev \
    libunwind-dev \
    libdw-dev \
    libdwarf \
    libdwarf-dev \
    elfutils-dev