FROM ubuntu:22.04

RUN apt-get update -qq && DEBIAN_FRONTEND="noninteractive" apt-get install -qq \
  libdwarf-dev \
    libdwarf1 \
    binutils-dev \
    libunwind-dev \
    libdw-dev \
    libssl-dev \
    build-essential \
    clang-format \
    libnuma-dev \
    numactl \
    libmbedtls-dev \
    libjemalloc-dev \
    git \
    wget \
    python3 \
    libsodium-dev \
    tar \
    p7zip \
    doxygen \
    graphviz \
    libbsd-dev \
    cmake \
    software-properties-common

RUN git clone https://github.com/tensorflow/tensorflow.git tensorflow_src && \
    cd tensorflow_src && \
    git checkout v2.6.0 && \
    cd .. && \
    mkdir tflite_build && \
    cd tflite_build && \
    cmake ../tensorflow_src/tensorflow/lite/c && \
    cmake --build . -j && \
    cd .. && \
    mkdir -p /usr/local/include/tensorflow/lite && \
    cp -R tensorflow_src/tensorflow/lite/* /usr/local/include/tensorflow/lite && \
    cp tflite_build/libtensorflowlite_c.so /lib/. && \
    ldconfig /lib && \
    rm -r tflite_build && \
    rm -r tensorflow_src

ENV BENCHMARK_SCRIPT_ARGS='-f ../../build/benchmark/ -nc -b (filter|map)-query-benchmark -m Run-with-docker'

# docker buildx, TARGETARCH,TARGETOS available in the intermediate container during build time
# We store new env variables for use during runtime/entrypoint
# more info: https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope
ARG TARGETARCH
ARG TARGETOS
# Docker's architectures do not map to the Debian ones (amd64=x86_64, arm64=aarch64)
# These are needed for defining lib paths later on CMake
RUN [ "$TARGETARCH" = "amd64" ] && echo "x86_64-linux-gnu" > /debian-triple || echo "aarch64-linux-gnu" > /debian-triple
ENV ACTUAL_TRIPLE='cat /debian-triple'

ADD ./entrypoint-nes-build.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

