//
// Created by pgrulich on 06.12.21.
//

#ifndef NES_INCLUDE_QUERYCOMPILER_IR_EXPRESSIONS_DIVNODE_HPP_
#define NES_INCLUDE_QUERYCOMPILER_IR_EXPRESSIONS_DIVNODE_HPP_

#endif//NES_INCLUDE_QUERYCOMPILER_IR_EXPRESSIONS_DIVNODE_HPP_
