# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    https://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Framework self-test for the per-connector sanitizer-suppression merge."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path

from conntest_runner.cli import (
    RunContext,
    _apply_plugin_suppressions,
    _find_plugin_suppressions,
    _merge_suppressions,
)


def _ctx(repo: Path, build: Path, env: dict[str, str]) -> RunContext:
    return RunContext(
        repo_root=repo,
        image="img",
        host_root=str(repo),
        container_repo="/c/repo",
        host_build_dir=build,
        container_build_dir="/c/repo/build",
        env=env,
    )


def _ship(conn_test_dir: Path, ext: str, body: str) -> None:
    conn_test_dir.mkdir(parents=True, exist_ok=True)
    (conn_test_dir / f"lib.{ext}").write_text(body, encoding="utf-8")


def test_merge_dedups_directives_and_drops_comments() -> None:
    a = "# rationale for Foo\nleak:Foo\nrace:Bar\n\n"
    b = "# a second connector's identical copy\nleak:Foo\nleak:Baz\n"
    out = _merge_suppressions([a, b])
    directives = [ln for ln in out.splitlines() if not ln.startswith("#")]
    # leak:Foo appears in both inputs but only once in the merge, first-seen order.
    assert directives == ["leak:Foo", "race:Bar", "leak:Baz"]
    # The generated artifact carries a header pointing back at the sources.
    assert out.startswith("# Generated by conntest")


def test_find_plugin_suppressions_globs_conn_test_dirs(tmp_path: Path) -> None:
    ct = tmp_path / "nes-plugins" / "Sources" / "Foo" / "conn-test"
    _ship(ct, "lsan-supp", "leak:Foo\n")
    _ship(ct, "tsan-supp", "race:Foo\n")
    assert _find_plugin_suppressions(tmp_path, "lsan-supp") == [ct / "lib.lsan-supp"]
    assert _find_plugin_suppressions(tmp_path, "tsan-supp") == [ct / "lib.tsan-supp"]


def test_apply_writes_merged_file_and_sets_options(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    build = tmp_path / "build"
    build.mkdir()
    # Two connectors ship an identical copy of the same library's suppressions.
    _ship(repo / "nes-plugins" / "Sources" / "Foo" / "conn-test", "lsan-supp", "leak:Shared\n")
    _ship(repo / "nes-plugins" / "Sinks" / "Bar" / "conn-test", "lsan-supp", "leak:Shared\n")
    _ship(repo / "nes-plugins" / "Sources" / "Foo" / "conn-test", "tsan-supp", "race:Shared\n")
    _ship(repo / "nes-plugins" / "Sinks" / "Bar" / "conn-test", "tsan-supp", "race:Shared\n")

    # ASAN_OPTIONS carries the address-lane toggle; LSAN_OPTIONS has a prior
    # value so we exercise the colon-append path.
    ctx = _ctx(repo, build, {"ASAN_OPTIONS": "detect_leaks=1", "LSAN_OPTIONS": "max_leaks=0"})
    _apply_plugin_suppressions(ctx)

    lsan = (build / "conntest-suppressions" / "conntest.lsan-supp").read_text(encoding="utf-8")
    # The duplicate copy is deduped — the directive appears exactly once.
    assert lsan.count("leak:Shared") == 1
    # LSan appends to its prior value with a colon, pointing at the *container* path.
    assert ctx.env["LSAN_OPTIONS"] == (
        "max_leaks=0:suppressions=/c/repo/build/conntest-suppressions/conntest.lsan-supp"
    )
    # TSan had no prior value, so it is set fresh.
    assert ctx.env["TSAN_OPTIONS"] == (
        "suppressions=/c/repo/build/conntest-suppressions/conntest.tsan-supp"
    )
    # The unrelated lane toggle is left untouched.
    assert ctx.env["ASAN_OPTIONS"] == "detect_leaks=1"


def test_apply_uses_tsan_space_separator(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    build = tmp_path / "build"
    build.mkdir()
    _ship(repo / "nes-plugins" / "Sources" / "Foo" / "conn-test", "tsan-supp", "race:Shared\n")

    ctx = _ctx(repo, build, {"TSAN_OPTIONS": "halt_on_error=1"})
    _apply_plugin_suppressions(ctx)

    assert ctx.env["TSAN_OPTIONS"] == (
        "halt_on_error=1 suppressions=/c/repo/build/conntest-suppressions/conntest.tsan-supp"
    )


def test_apply_is_noop_without_suppression_files(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    (repo / "nes-plugins").mkdir(parents=True)
    build = tmp_path / "build"
    build.mkdir()

    ctx = _ctx(repo, build, {})
    _apply_plugin_suppressions(ctx)

    assert "LSAN_OPTIONS" not in ctx.env
    assert "TSAN_OPTIONS" not in ctx.env
    assert not (build / "conntest-suppressions").exists()
