//
// Created by pgrulich on 31.07.23.
//

#ifndef NES_NES_RUNTIME_INCLUDE_EXECUTION_OPERATORS_STREAMING_AGGREGATIONS_WINDOWTYPE_HPP_
#define NES_NES_RUNTIME_INCLUDE_EXECUTION_OPERATORS_STREAMING_AGGREGATIONS_WINDOWTYPE_HPP_
namespace NES::Runtime::Execution::Operators {
enum WindowType { TumblingWindow, SlidingWindow };
}
#endif//NES_NES_RUNTIME_INCLUDE_EXECUTION_OPERATORS_STREAMING_AGGREGATIONS_WINDOWTYPE_HPP_
