name: Run Command in Container
description: |
  Runs script or command directly in a development container. The container is mounted in the current working directory
  and uses the current user.

inputs:
  image_name:
    description: 'name of the docker image to use'
    required: true
  run:
    description: 'bash command(s) to run within the container'
    required: true
  sccache_bucket:
    description: 'S3 bucket for sccache'
    required: false
    default: ''
  sccache_endpoint:
    description: 'S3 endpoint for sccache'
    required: false
    default: ''
  aws_access_key_id:
    description: 'AWS access key ID for sccache'
    required: false
    default: ''
  aws_secret_access_key:
    description: 'AWS secret access key for sccache'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: run in container
      shell: bash
      run: |
        docker run \
             -v $(pwd):$(pwd) \
             -e SCCACHE_DIR=$(pwd)/.sccache \
             -e SCCACHE_BUCKET="${{ inputs.sccache_bucket }}" \
             -e SCCACHE_ENDPOINT="${{ inputs.sccache_endpoint }}" \
             -e SCCACHE_REGION=auto \
             -e SCCACHE_S3_USE_SSL=true \
             -e AWS_ACCESS_KEY_ID="${{ inputs.aws_access_key_id }}" \
             -e AWS_SECRET_ACCESS_KEY="${{ inputs.aws_secret_access_key }}" \
             --workdir $(pwd) -u $(id -u):$(id -g) \
             ${{inputs.image_name}} \
              /usr/bin/bash -c '${{inputs.run}}'
