name: Run Command in Container
description: |
  Runs script or command directly in a development container. The container is mounted in the current working directory
  and uses the current user.

inputs:
  image_name:
    description: 'name of the docker image to use'
    required: true
  run:
    description: 'bash command(s) to run within the container'
    required: true

runs:
  using: 'composite'
  steps:
    - name: run in container
      shell: bash
      run: |
        docker run \
             -v /var/run/docker.sock:/var/run/docker.sock \
             --group-add $(stat -c '%g' /var/run/docker.sock) \
             -v $(pwd):$(pwd) -e CCACHE_DIR=$(pwd)/.ccache -e HOME=$(pwd) --workdir $(pwd) -u $(id -u):$(id -g) \
             ${{inputs.image_name}} \
              /usr/bin/bash -c '${{inputs.run}}'
