[package]
name = "rust-lib-cbg"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[build-dependencies]
cbindgen = "0.29.0"

[features]
default = ["file-source", "file-sink", "checksum-sink"]
file-source = []
file-sink = []
checksum-sink = []

