/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/
#include <Rules/Static/WatermarkAssignerPushdownRule.hpp>

#include <ranges>
#include <set>
#include <string_view>
#include <typeindex>
#include <typeinfo>
#include <unordered_set>
#include <utility>
#include <vector>

#include <DataTypes/TimeUnit.hpp>
#include <Functions/FieldAccessLogicalFunction.hpp>
#include <Operators/EventTimeWatermarkAssignerLogicalOperator.hpp>
#include <Operators/IngestionTimeWatermarkAssignerLogicalOperator.hpp>
#include <Operators/LogicalOperator.hpp>
#include <Operators/LogicalOperatorFwd.hpp>
#include <Operators/ProjectionLogicalOperator.hpp>
#include <Operators/SelectionLogicalOperator.hpp>
#include <Operators/Sinks/SinkLogicalOperator.hpp>
#include <Operators/Sources/SourceDescriptorLogicalOperator.hpp>
#include <Operators/UnionLogicalOperator.hpp>
#include <Plans/LogicalPlan.hpp>
#include <Rules/Barriers/FixedPlanStructureBarrier.hpp>
#include <Rules/Barriers/SemanticAnalysisBarrier.hpp>
#include <Rules/Static/PredicatePushdownRule.hpp>
#include <Schema/Field.hpp>
#include <ErrorHandling.hpp>

namespace NES
{
namespace
{
LogicalOperator
watermarkAssignerPushdown(const LogicalOperator& op, bool ingestionTime, std::vector<std::pair<Field, Windowing::TimeUnit>> eventTime);

LogicalOperator
addWatermarkAssigners(LogicalOperator op, const bool ingestionTime, std::vector<std::pair<Field, Windowing::TimeUnit>> eventTime)
{
    /// adds all required watermark assigners

    if (ingestionTime)
    {
        op = TypedLogicalOperator<IngestionTimeWatermarkAssignerLogicalOperator>{op};
    }
    while (!eventTime.empty())
    {
        auto [onField, unit] = eventTime.back();
        auto field = op.getOutputSchema()[onField.getLastName()];
        PRECONDITION(field.has_value(), "the operator must have the event time field");
        eventTime.pop_back();
        op = TypedLogicalOperator<EventTimeWatermarkAssignerLogicalOperator>{op, FieldAccessLogicalFunction{field.value()}, unit};
    }
    return op;
}

std::vector<std::pair<Field, Windowing::TimeUnit>>
fieldsWithNewBase(const LogicalOperator& base, std::vector<std::pair<Field, Windowing::TimeUnit>> eventTime)
{
    for (auto& field : eventTime | std::views::keys)
    {
        auto childField = base.getOutputSchema()[field.getLastName()];
        PRECONDITION(childField.has_value(), "the operator must have the event time field");
        field = childField.value();
    }
    return eventTime;
}

LogicalOperator
applyToAllChildren(const LogicalOperator& op, const bool ingestionTime, const std::vector<std::pair<Field, Windowing::TimeUnit>>& eventTime)
{
    std::vector<LogicalOperator> children;
    for (const auto& child : op.getChildren())
    {
        const auto childEventTime = fieldsWithNewBase(child, eventTime);
        auto newChild = watermarkAssignerPushdown(child, ingestionTime, childEventTime);
        children.push_back(newChild);
    }
    return op.withChildren(children).withInferredSchema();
}

LogicalOperator pushBeyondSink(const TypedLogicalOperator<SinkLogicalOperator>& op)
{
    /// Sinks are the starting point of the recursion.
    /// Because they don't have parents, no watermark assigner
    /// has to be pushed here.
    /// The recursion starts thus with an empty event time watermark assigner set,
    /// and no ingestion time watermark assigner.
    auto newChild = watermarkAssignerPushdown(op->getChild(), {}, {});
    return op->withChildren({newChild}).withInferredSchema();
}

LogicalOperator pushBeyondSource(
    const TypedLogicalOperator<SourceDescriptorLogicalOperator>& op,
    bool ingestionTime,
    std::vector<std::pair<Field, Windowing::TimeUnit>> eventTime)
{
    return addWatermarkAssigners(op, std::move(ingestionTime), std::move(eventTime));
}

LogicalOperator pushBeyondTransparentOperator(
    const LogicalOperator& op, bool ingestionTime, const std::vector<std::pair<Field, Windowing::TimeUnit>>& eventTime)
{
    /// Pushes watermark assigners beyond operators that do not affect the
    /// watermark assigners.
    return applyToAllChildren(op, std::move(ingestionTime), eventTime);
}

LogicalOperator pushBeyondProjection(
    const TypedLogicalOperator<ProjectionLogicalOperator>& op,
    bool ingestionTime,
    const std::vector<std::pair<Field, Windowing::TimeUnit>>& eventTime)
{
    /// test if event time fields are generated by projection.
    /// If not, they are pushed further.
    /// If they are, the event time watermark assigner is applied.

    std::unordered_set<Field> pushableFields;
    if (op->hasAsterisk())
    {
        for (const auto& childField : op->getChild().getOutputSchema())
        {
            auto field = op.getOutputSchema()[childField.getLastName()];
            INVARIANT(field.has_value(), "If projection has asterisk, all child fields must be available without renaming");
            pushableFields.emplace(field.value());
        }
    }

    for (const auto& [field, function] : op->getProjections())
    {
        if (auto fieldAccess = function.tryGetAs<FieldAccessLogicalFunction>(); fieldAccess.has_value())
        {
            auto newField = field.getLastName();
            auto originalField = fieldAccess.value()->getField().getLastName();

            if (newField == originalField)
            {
                pushableFields.emplace(field);
            }
        }
    }

    std::vector<std::pair<Field, Windowing::TimeUnit>> pushFurther{};
    std::vector<std::pair<Field, Windowing::TimeUnit>> applyNow{};

    for (const auto& [onField, unit] : eventTime)
    {
        auto pushable = pushableFields.contains(onField);
        if (pushable)
        {
            pushFurther.emplace_back(onField, unit);
        }
        else
        {
            applyNow.emplace_back(onField, unit);
        }
    }

    auto newOp = applyToAllChildren(op, ingestionTime, pushFurther);

    for (const auto& [onField, unit] : std::ranges::reverse_view(applyNow))
    {
        auto field = newOp.getOutputSchema()[onField.getLastName()];
        PRECONDITION(field.has_value(), "the operator must have the event time field");
        newOp = TypedLogicalOperator<EventTimeWatermarkAssignerLogicalOperator>(newOp, FieldAccessLogicalFunction{field.value()}, unit);
    }
    return newOp;
}

LogicalOperator pushBeyondEventTimeWatermarkAssigner(
    const TypedLogicalOperator<EventTimeWatermarkAssignerLogicalOperator>& op,
    const bool ingestionTime,
    std::vector<std::pair<Field, Windowing::TimeUnit>> eventTime)
{
    /// Adds relevant metadata to eventTime variable to push the assigner further down if possible
    /// Does not push event time water mark assigners that don't use a FieldAccessLogicalFunction.

    INVARIANT(
        op->getOnField().tryGetAs<FieldAccessLogicalFunction>().has_value(),
        "EventTime watermark assigner onField must be a FieldAccessLogicalFunction");

    const auto fieldAccess = op->getOnField().tryGetAs<FieldAccessLogicalFunction>();
    eventTime = fieldsWithNewBase(op->getChild(), eventTime);
    eventTime.emplace_back(fieldAccess.value()->getField(), op->getUnit());
    return watermarkAssignerPushdown(op->getChild(), ingestionTime, eventTime);
}

LogicalOperator pushBeyondIngestionTimeWatermarkAssigner(
    const TypedLogicalOperator<IngestionTimeWatermarkAssignerLogicalOperator>& op,
    bool /* ingestionTime */,
    std::vector<std::pair<Field, Windowing::TimeUnit>> eventTime)
{
    /// Adds flag that a ingestion time watermark assigner is required

    eventTime = fieldsWithNewBase(op->getChild(), eventTime);
    return watermarkAssignerPushdown(op->getChild(), true, eventTime);
}

LogicalOperator
pushBeyondDefault(const LogicalOperator& op, const bool ingestionTime, std::vector<std::pair<Field, Windowing::TimeUnit>> eventTime)
{
    /// Implements default behavior if operator is not explicitly handled.
    /// Applies all watermark assigners and restarts recursion for all children.
    auto newOp = applyToAllChildren(op, false, {});
    return addWatermarkAssigners(std::move(newOp), ingestionTime, std::move(eventTime));
}

LogicalOperator
watermarkAssignerPushdown(const LogicalOperator& op, bool ingestionTime, std::vector<std::pair<Field, Windowing::TimeUnit>> eventTime)
{
    if (const auto sink = op.tryGetAs<SinkLogicalOperator>())
    {
        return pushBeyondSink(sink.value());
    }
    if (const auto source = op.tryGetAs<SourceDescriptorLogicalOperator>())
    {
        return pushBeyondSource(source.value(), std::move(ingestionTime), std::move(eventTime));
    }
    if (const auto eventTimeWA = op.tryGetAs<EventTimeWatermarkAssignerLogicalOperator>())
    {
        return pushBeyondEventTimeWatermarkAssigner(eventTimeWA.value(), std::move(ingestionTime), std::move(eventTime));
    }
    if (const auto ingestionTimeWatermarkAssigner = op.tryGetAs<IngestionTimeWatermarkAssignerLogicalOperator>())
    {
        return pushBeyondIngestionTimeWatermarkAssigner(
            ingestionTimeWatermarkAssigner.value(), std::move(ingestionTime), std::move(eventTime));
    }
    if (op.tryGetAs<SelectionLogicalOperator>().has_value() || op.tryGetAs<UnionLogicalOperator>().has_value())
    {
        return pushBeyondTransparentOperator(op, std::move(ingestionTime), eventTime);
    }
    if (const auto projOp = op.tryGetAs<ProjectionLogicalOperator>())
    {
        return pushBeyondProjection(projOp.value(), std::move(ingestionTime), eventTime);
    }

    return pushBeyondDefault(op, std::move(ingestionTime), std::move(eventTime));
}

}

/// NOLINTNEXTLINE(readability-convert-member-functions-to-static)
LogicalPlan WatermarkAssignerPushdownRule::apply(LogicalPlan queryPlan) const
{
    auto originalRoots = queryPlan.getRootOperators();
    PRECONDITION(originalRoots.size() == 1, "watermark pushdown not yet implemented for more than one root");
    auto newRoot = watermarkAssignerPushdown(originalRoots.at(0), false, {});
    queryPlan = queryPlan.withRootOperators({newRoot});
    return queryPlan;
}

/// NOLINTNEXTLINE(readability-convert-member-functions-to-static)
std::set<std::type_index> WatermarkAssignerPushdownRule::needs() const
{
    return {typeid(SemanticAnalysisBarrier)};
}

/// NOLINTNEXTLINE(readability-convert-member-functions-to-static)
std::set<std::type_index> WatermarkAssignerPushdownRule::wants() const
{
    return {typeid(PredicatePushdownRule)};
}

/// NOLINTNEXTLINE(readability-convert-member-functions-to-static)
std::set<std::type_index> WatermarkAssignerPushdownRule::neededBy() const
{
    return {typeid(FixedPlanStructureBarrier)};
}


}
