FROM nebulastream/nes-build-image:latest

RUN ls ../
ADD ./resources/*.deb nes.deb
RUN dpkg -i nes.deb && \
    apt install iputils-ping iproute2 ifupdown net-tools -y -qq && \
    apt autoclean -y -qq
RUN rm nes.deb


CMD /bin/bash
