[package]
name = "nes-benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
chrono = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tempfile = "3.8"
futures = "0.3"
async-trait = "0.1"
walkdir = "2.4"
rand = "0.9.2"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.27", features = ["signal", "process"] }

[[bin]]
name = "nes-benchmark"
path = "src/main.rs"

[[bin]]
name = "tcp-client"
path = "src/tcp_client.rs"

[[bin]]
name = "tcp-server"
path = "src/tcp_server.rs"

[[bin]]
name = "tcp-server-enhanced"
path = "src/tcp_server_enhanced.rs"