/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#pragma once

#include <vector>
#include <Plugins/PluginDescriptor.hpp>

namespace NES
{

/// Collects the describe functions of all built-in (statically linked) registries and plugin
/// entries in this binary. Built-in plugins implement the same describe interface as dynamic
/// plugins (PluginDescribeFn); only the transport differs — the glue TUs generated by
/// cmake/RuntimeRegistrationUtil.cmake append FUNCTION POINTERS here at static-initialization
/// time (trivial, order-independent bookkeeping) where a dynamic plugin's aggregated
/// nes_plugin_describe is resolved via dlsym. loadBuiltinPlugins() assembles one
/// PluginDescriptor from them and hands it to the PluginLoader, which performs the actual
/// registration.
class BuiltinPlugins
{
public:
    static BuiltinPlugins& instance();

    BuiltinPlugins(const BuiltinPlugins&) = delete;
    BuiltinPlugins(BuiltinPlugins&&) noexcept = delete;
    BuiltinPlugins& operator=(const BuiltinPlugins&) = delete;
    BuiltinPlugins& operator=(BuiltinPlugins&&) noexcept = delete;
    ~BuiltinPlugins() = default;

    void addDescriber(PluginDescribeFn describer) { describers.push_back(describer); }

    /// Assembles the descriptor of everything statically linked into this binary.
    [[nodiscard]] PluginDescriptor describe() const;

private:
    BuiltinPlugins() = default;

    std::vector<PluginDescribeFn> describers;
};

/// Announces all built-in registries, then registers all built-in plugin entries — the same
/// two-phase protocol dynamically loaded plugins go through. Call once at process startup,
/// before any registry-backed functionality is used (the frontends and the shared test main do;
/// constructing a PluginCatalog does as well). Idempotent and thread-safe. Throws
/// CannotLoadPlugin if a registration fails.
void loadBuiltinPlugins();

}
