/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#pragma once

#include <any>
#include <cstdint>
#include <functional>
#include <memory>
#include <string>
#include <utility>
#include <vector>

namespace NES
{

enum class InsertResult : uint8_t
{
    Success,
    DuplicateKey,
    EntryTypeMismatch,
};

/// A registry a plugin makes available to the plugin system. Carries a type-erased pointer to the
/// registry singleton plus a type-erased inserter bound to the concrete registry type, so the
/// plugin system can register entries into it without knowing their types (see provideRegistry).
struct RegistryProvision
{
    std::string registryClassName;
    /// identity of the singleton, for idempotent re-provision checks
    const void* instanceAddress = nullptr;
    std::function<InsertResult(const std::string& key, const std::any& entry)> insertEntry;
};

/// An entry a plugin contributes to a registry. Pure data: the plugin system performs the actual
/// registration (and owns the duplicate/missing-registry/type policies, see PluginLoader).
struct EntryProvision
{
    std::string registryClassName;
    std::string key;
    /// must hold exactly the registry's EntryType (the generated glue coerces to it)
    std::any entry;
    /// optional entries are skipped when the host does not know the registry; required entries
    /// fail the load instead
    bool optional = false;
};

/// Everything a plugin provides to the plugin system, produced by the generated
/// nes_plugin_describe entry point (dynamic plugins) or collected via BuiltinPlugins (built-in
/// plugins). Plugins only describe; they never register anything themselves.
struct PluginDescriptor
{
    /// for diagnostics: module path or "builtin"
    std::string name;
    std::vector<RegistryProvision> registries;
    std::vector<EntryProvision> entries;
};

/// The describe interface every plugin implements (generated by
/// cmake/RuntimeRegistrationUtil.cmake): built-in plugins collect pointers to such functions in
/// BuiltinPlugins at static-initialization time; dynamic plugins export one aggregated
/// nes_plugin_describe of this signature that the PluginCatalog resolves via dlsym.
using PluginDescribeFn = void (*)(PluginDescriptor&);

/// Creates the provision for a concrete registry; the inserter closes over the registry type,
/// which is what allows the plugin system to stay type-erased.
template <typename Registry>
RegistryProvision provideRegistry(std::string registryClassName)
{
    return RegistryProvision{
        .registryClassName = std::move(registryClassName),
        .instanceAddress = std::addressof(Registry::instance()),
        .insertEntry = [](const std::string& key, const std::any& entry)
        {
            const auto* typedEntry = std::any_cast<typename Registry::EntryType>(&entry);
            if (typedEntry == nullptr)
            {
                return InsertResult::EntryTypeMismatch;
            }
            return Registry::instance().addEntry(key, *typedEntry) ? InsertResult::Success : InsertResult::DuplicateKey;
        }};
}

}
