/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#pragma once

#include <Plugins/PluginDescriptor.hpp>

namespace NES
{

/// Bump on any change to the plugin entry-point contract or the registry ABI.
/// Version history:
///   1: nes_plugin_abi_version + nes_plugin_register(PluginRegistrar&) (type since renamed)
///   2: added the announce phase: nes_plugin_announce + register hook by const&
///   3: descriptor protocol: single nes_plugin_describe(PluginDescriptor&) hook; plugins only
///      describe their registries/entries, the host's PluginLoader performs registration
inline constexpr int PLUGIN_ABI_VERSION = 3;

/// Signature of the version entry point every dynamic plugin exports; the describe entry point
/// uses PluginDescribeFn from PluginDescriptor.hpp
/// (both generated by finalize_dynamic_plugin in cmake/RuntimeRegistrationUtil.cmake).
using PluginAbiVersionFn = int (*)();

}
