/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#pragma once

#include <filesystem>
#include <mutex>
#include <vector>

namespace NES
{

/// Owns the runtime-loaded plugins of this process and drives the load protocol. A plugin links
/// against the shared core (libnes) and exports two entry points, generated by
/// finalize_dynamic_plugin in cmake/RuntimeRegistrationUtil.cmake:
///     extern "C" int nes_plugin_abi_version();
///     extern "C" void nes_plugin_describe(NES::PluginDescriptor&);
/// Loading runs in three phases across all requested plugins: (1) dlopen everything — passive,
/// no registration side effects; (2) validate the ABI and collect every plugin's descriptor;
/// (3) the PluginLoader registers everything — the registries of all plugins before the
/// entries of any plugin. This makes registrations independent of plugin load order, so a
/// plugin can contribute to a registry another plugin declared, and keeps all registration
/// policy (duplicates, missing registries, optional entries) in the registrar.
/// Loading is idempotent per canonical path: re-loading an already-loaded shared object is a
/// no-op. Plugins stay loaded for the lifetime of the process; there is no unloading, and the
/// manager's destruction does not dlclose anything.
/// Constructing the manager runs loadBuiltinPlugins(), so dynamically loaded plugins can resolve
/// the built-in registries.
class PluginCatalog
{
public:
    struct LoadedPlugin
    {
        std::filesystem::path path;
        void* handle = nullptr;
    };

    PluginCatalog();

    PluginCatalog(const PluginCatalog&) = delete;
    PluginCatalog(PluginCatalog&&) noexcept = delete;
    PluginCatalog& operator=(const PluginCatalog&) = delete;
    PluginCatalog& operator=(PluginCatalog&&) noexcept = delete;
    ~PluginCatalog() = default;

    /// Throws CannotLoadPlugin if a shared object cannot be opened, does not export the entry
    /// points, was built against a different PLUGIN_ABI_VERSION, or fails to register. On
    /// failure none of the requested plugins are recorded as loaded, but entries registered
    /// before the failure remain (there is no rollback) — treat a failed load as fatal.
    void load(const std::vector<std::filesystem::path>& paths);

    /// Loads ':'-separated shared-object paths from the NES_PLUGINS environment variable.
    /// No-op if the variable is unset or empty.
    void loadFromEnvironment();

    [[nodiscard]] std::vector<LoadedPlugin> loadedPlugins() const;

private:
    mutable std::mutex mutex;
    std::vector<LoadedPlugin> plugins;
};

}
