#ifndef UTILITY_FUNCTIONS_HPP
#define UTILITY_FUNCTIONS_HPP

#include <string>
#include <API/InputQuery.hpp>

/**
 * @brief a collection of shared utility functions
 */
namespace iotdb {

class UtilityFunctions {
 public:
// removes leading and trailing whitespaces
  static std::string trim(std::string s);

  /**
   *  @brief this function **executes** the code provided by the user and returns an InputQuery Object
   *  @caution: this function will replace the stream name "xyz" provided by the user with the stream generated by the system and fetched from the catalog
   *  @param query as a string
   *  @return Smart pointer to InputQuery object of the query
   *  */
  static InputQueryPtr createQueryFromCodeString(
      const std::string& query_code_snippet);

  /**
   *  @brief this function **executes** the code provided by the user and returns an schema Object
   *  @param query as a string
   *  @return Smart pointer to InputQuery object of the query
   *  */
  static SchemaPtr createSchemaFromCode(const std::string& query_code_snippet);

};
}

#endif /* UTILITY_FUNCTIONS_HPP */
