#pragma once
// Stub protobuf header for WASM build -- serialization not needed for validation
// The real header is generated by protoc during the native NES build.

namespace google::protobuf {
class MessageLite {
public:
    virtual ~MessageLite() = default;
    std::string SerializeAsString() const { return ""; }
};
} // namespace google::protobuf

class SerializableVariantDescriptor : public google::protobuf::MessageLite {};
