#ifndef NES_INCLUDE_NODES_EXPRESSIONS_BINARYOPERATIONTYPE_HPP_
#define NES_INCLUDE_NODES_EXPRESSIONS_BINARYOPERATIONTYPE_HPP_

enum BinaryOperationType {
    EQUAL_OP,
    UNEQUAL_OP,
    LESS_THEN_OP,
    LESS_THEN_EQUAL_OP,
    GREATER_THEN_OP,
    GREATER_THEN_EQUAL_OP,
    LOGICAL_AND_OP,
    LOGICAL_OR_OP,
    BITWISE_AND_OP,
    BITWISE_OR_OP,
    BITWISE_XOR_OP,
    BITWISE_LEFT_SHIFT_OP,
    BITWISE_RIGHT_SHIFT_OP
};



#endif //NES_INCLUDE_NODES_EXPRESSIONS_BINARYOPERATIONTYPE_HPP_
