if (NES_CODE_COVERAGE)
    set(CODE_COVERAGE ON)
endif ()

function(add_nes_ut_test TARGET_NAME FILE_PATH)
    add_executable(${TARGET_NAME} ${FILE_PATH})
    target_link_libraries(${TARGET_NAME} nes-tests)
    if (CODE_COVERAGE)
        target_code_coverage(${TARGET_NAME} AUTO ALL EXTERNAL EXCLUDE tests/*)
        message(STATUS "Added cc test ${TARGET_NAME}")
    endif ()
    add_test(NAME ${TARGET_NAME} COMMAND ${TARGET_NAME})
    message(STATUS "Added ut test ${TARGET_NAME}")
endfunction()

function(add_nes_it_test TARGET_NAME FILE_PATH)
    add_executable(${TARGET_NAME} ${FILE_PATH})
    target_link_libraries(${TARGET_NAME} nes-tests)
    add_test(NAME ${TARGET_NAME} COMMAND ${TARGET_NAME})
    message(STATUS "Added it test ${TARGET_NAME}")
endfunction()

function(enable_extra_test_features)
    if (CODE_COVERAGE)
        add_code_coverage_all_targets(EXCLUDE tests/*)
    endif ()
endfunction()