# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    https://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# RustLibCollection.cmake — Transitive Rust crate collection and per-executable umbrella generation.
#
# Multiple Rust staticlib crates (e.g. nes_source_bindings, nes_network_bindings) each embed
# the CXX runtime, producing duplicate symbols when linked together. This module:
#
#   1. Tracks which Rust crates each C++ target needs (via INTERFACE properties)
#   2. At executable link time, walks the transitive dependency graph to collect all needed crates
#   3. For multi-crate executables, generates a per-executable umbrella staticlib that bundles
#      exactly those crates — deduplicating shared deps (CXX, tokio, etc.)
#
# The umbrella is a standalone crate generated in ${CMAKE_BINARY_DIR}/rust-umbrellas/<exe>/,
# with path dependencies pointing at the source-tree crate directories. Individual crate
# Cargo.toml files must include "rlib" in crate-type so they can be used as dependencies.

# Register a Rust crate's source directory so the umbrella generator can find it.
function(register_rust_crate rust_crate manifest_dir)
    set_property(GLOBAL PROPERTY NES_RUST_CRATE_${rust_crate}_PATH "${manifest_dir}")
    set_property(GLOBAL APPEND PROPERTY NES_RUST_CRATE_NAMES "${rust_crate}")
endfunction()

# Generate a Cargo workspace Cargo.toml from a list of member directories.
#
# Usage:
#   generate_rust_workspace(nes-sources/rust nes-buffer-bindings nes-source-bindings ...)
#
# The first argument is the workspace directory (containing Cargo.toml).
# Remaining arguments are member directory names relative to the workspace dir.
# The generated file has an AUTO-GENERATED comment so developers know not to edit it.
function(generate_rust_workspace workspace_dir)
    set(members ${ARGN})
    set(members_toml "")
    foreach (member ${members})
        string(APPEND members_toml "    \"${member}\",\n")
    endforeach ()
    file(WRITE "${workspace_dir}/Cargo.toml"
            "# AUTO-GENERATED by CMake (generate_rust_workspace). Do not edit.
[workspace]
resolver = \"2\"
members = [
${members_toml}]
")
endfunction()

# Add per-crate `cargo test` as ctest tests for a Rust workspace.
#
# Usage:
#   add_rust_cargo_tests(nes-sources/rust nes_buffer_bindings nes_source_runtime ...)
#
# Creates one ctest test per crate named "rust-<crate_name>".
# Tests are only added when NES_ENABLES_TESTS is ON.
# Uses the same Cargo binary and toolchain that Corrosion detected to avoid
# mismatches with rust-toolchain.toml overrides.
function(add_rust_cargo_tests workspace_dir)
    if (NOT NES_ENABLES_TESTS)
        return()
    endif ()

    # Determine the toolchain version Corrosion detected so we can override
    # any rust-toolchain.toml in the workspace. This ensures `cargo test` uses
    # the same compiler as the main build.
    get_property(_cargo_version CACHE _CORROSION_CARGO_VERSION PROPERTY VALUE)
    set(_test_env "RUSTUP_TOOLCHAIN=${_cargo_version}")
    if (NES_RUST_ENV_VARS)
        list(APPEND _test_env ${NES_RUST_ENV_VARS})
    endif ()

    set(crate_names ${ARGN})
    set(_prev_test "")
    foreach (crate ${crate_names})
        add_test(
                NAME "rust-${crate}"
                COMMAND "${_CORROSION_CARGO}" test -p ${crate} --color=always
                WORKING_DIRECTORY "${workspace_dir}"
        )
        set_tests_properties("rust-${crate}" PROPERTIES
                ENVIRONMENT "${_test_env}"
                LABELS "rust"
        )
        # Serialize Rust tests to avoid parallel cargo/rustup conflicts
        # (shared target directory, potential toolchain downloads).
        if (_prev_test)
            set_tests_properties("rust-${crate}" PROPERTIES
                    DEPENDS "${_prev_test}")
        endif ()
        set(_prev_test "rust-${crate}")
    endforeach ()
endfunction()

# Declare that a C++ target requires a Rust crate at link time.
# This propagates transitively through target_link_libraries chains via INTERFACE properties.
#
# Usage:
#   target_link_rust_lib(<cpp_target> <rust_crate>
#                        [NO_DEFAULT_FEATURES]
#                        [FEATURES <feat1> <feat2> ...])
#
# When FEATURES or NO_DEFAULT_FEATURES is used, the entry is encoded as
# "crate|ndf|feat1,feat2" so the umbrella generator can emit the feature list
# into its generated Cargo.toml. Consumers that request different feature sets
# of the same crate get separate umbrellas (the hash includes feature config).
function(target_link_rust_lib cpp_target rust_crate)
    cmake_parse_arguments(PARSE_ARGV 2 ARG "NO_DEFAULT_FEATURES" "" "FEATURES")
    set(_entry "${rust_crate}")
    if (ARG_NO_DEFAULT_FEATURES OR ARG_FEATURES)
        set(_ndf "0")
        if (ARG_NO_DEFAULT_FEATURES)
            set(_ndf "1")
        endif ()
        string(JOIN "," _feats ${ARG_FEATURES})
        set(_entry "${rust_crate}|${_ndf}|${_feats}")
    endif ()
    set_property(TARGET ${cpp_target} APPEND PROPERTY
            INTERFACE_NES_RUST_LIBS "${_entry}")
endfunction()

# Remove Corrosion's automatic link from a CXX bridge target to its Rust crate.
# This prevents the individual Rust staticlib from being pulled into every exe that links
# the bridge target. The actual Rust symbols come from target_link_rust() instead.
# Also registers the bridge target so the umbrella can link it.
function(cxxbridge_remove_rust_link bridge_target rust_crate)
    # Register this bridge target for umbrella linking.
    set_property(GLOBAL PROPERTY NES_CXX_BRIDGE_${rust_crate} "${bridge_target}")
    # Corrosion may name the imported target with a -static suffix
    set(_variants "${rust_crate}" "${rust_crate}-static")
    # Remove from LINK_LIBRARIES (PRIVATE deps added by corrosion_add_cxxbridge)
    get_target_property(libs ${bridge_target} LINK_LIBRARIES)
    if (libs)
        foreach (_v ${_variants})
            list(REMOVE_ITEM libs "${_v}")
        endforeach ()
        set_target_properties(${bridge_target} PROPERTIES LINK_LIBRARIES "${libs}")
    endif ()
    # Also remove from INTERFACE_LINK_LIBRARIES — Corrosion adds $<LINK_ONLY:crate> there
    get_target_property(iface_libs ${bridge_target} INTERFACE_LINK_LIBRARIES)
    if (iface_libs)
        foreach (_v ${_variants})
            list(REMOVE_ITEM iface_libs "${_v}")
            list(REMOVE_ITEM iface_libs "$<LINK_ONLY:${_v}>")
        endforeach ()
        set_target_properties(${bridge_target} PROPERTIES INTERFACE_LINK_LIBRARIES "${iface_libs}")
    endif ()
endfunction()

# Collect all Rust crates transitively required by a target.
# Walks LINK_LIBRARIES and INTERFACE_LINK_LIBRARIES, collecting INTERFACE_NES_RUST_LIBS.
function(collect_transitive_rust_libs target out_var)
    set_property(GLOBAL PROPERTY _NES_RUST_COLLECT_VISITED "")
    set_property(GLOBAL PROPERTY _NES_RUST_COLLECT_RESULT "")
    _collect_rust_libs_recursive(${target})
    get_property(result GLOBAL PROPERTY _NES_RUST_COLLECT_RESULT)
    list(REMOVE_DUPLICATES result)
    set(${out_var} "${result}" PARENT_SCOPE)
endfunction()

function(_collect_rust_libs_recursive target)
    get_property(visited GLOBAL PROPERTY _NES_RUST_COLLECT_VISITED)
    if ("${target}" IN_LIST visited)
        return()
    endif ()
    set_property(GLOBAL APPEND PROPERTY _NES_RUST_COLLECT_VISITED "${target}")

    if (NOT TARGET ${target})
        return()
    endif ()

    get_target_property(rust_libs ${target} INTERFACE_NES_RUST_LIBS)
    if (rust_libs)
        set_property(GLOBAL APPEND PROPERTY _NES_RUST_COLLECT_RESULT ${rust_libs})
    endif ()

    foreach (prop LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
        get_target_property(deps ${target} ${prop})
        if (deps)
            foreach (dep ${deps})
                if (TARGET ${dep})
                    _collect_rust_libs_recursive(${dep})
                endif ()
            endforeach ()
        endif ()
    endforeach ()
endfunction()

# Register an executable for deferred Rust link processing.
function(target_link_rust exe_target)
    set_property(GLOBAL APPEND PROPERTY _NES_RUST_EXE_TARGETS "${exe_target}")
endfunction()

# Process all accumulated target_link_rust requests (called via cmake_language(DEFER)).
function(_finalize_rust_links)
    get_property(targets GLOBAL PROPERTY _NES_RUST_EXE_TARGETS)
    if (NOT targets)
        return()
    endif ()
    foreach (exe_target IN LISTS targets)
        _target_link_rust_impl("${exe_target}")
    endforeach ()
endfunction()

# Deferred implementation of target_link_rust.
function(_target_link_rust_impl exe_target)
    if (NOT TARGET ${exe_target})
        return()
    endif ()

    get_target_property(already_linked ${exe_target} _NES_RUST_LINKED)
    if (already_linked)
        return()
    endif ()

    collect_transitive_rust_libs(${exe_target} rust_libs)
    list(LENGTH rust_libs num_libs)

    if (num_libs EQUAL 0)
        return()
    endif ()

    set_target_properties(${exe_target} PROPERTIES _NES_RUST_LINKED TRUE)

    # Parse encoded entries ("crate" or "crate|ndf|feat1,feat2") into a unique
    # crate list plus per-crate merged feature config. Multiple entries for the
    # same crate union their features and OR their no-default-features flag,
    # matching how cargo unifies features across a dep graph.
    set(_crates "")
    foreach (entry IN LISTS rust_libs)
        string(REPLACE "|" ";" _parts "${entry}")
        list(LENGTH _parts _n)
        list(GET _parts 0 _crate)
        list(APPEND _crates "${_crate}")
        if (_n GREATER_EQUAL 3)
            list(GET _parts 1 _ndf)
            list(GET _parts 2 _feats_str)
            get_property(_existing GLOBAL PROPERTY _NES_UMB_${exe_target}_${_crate}_FEATS)
            if (_feats_str)
                string(REPLACE "," ";" _feats "${_feats_str}")
                list(APPEND _existing ${_feats})
                list(REMOVE_DUPLICATES _existing)
            endif ()
            set_property(GLOBAL PROPERTY _NES_UMB_${exe_target}_${_crate}_FEATS "${_existing}")
            if (_ndf STREQUAL "1")
                set_property(GLOBAL PROPERTY _NES_UMB_${exe_target}_${_crate}_NDF 1)
            endif ()
        endif ()
    endforeach ()
    list(REMOVE_DUPLICATES _crates)
    list(SORT _crates)

    # Fold per-crate feature config into the umbrella hash so consumers picking
    # different feature sets of the same crate get distinct umbrella staticlibs.
    set(_crate_key "")
    foreach (crate IN LISTS _crates)
        get_property(_f GLOBAL PROPERTY _NES_UMB_${exe_target}_${crate}_FEATS)
        get_property(_ndf GLOBAL PROPERTY _NES_UMB_${exe_target}_${crate}_NDF)
        if (_f)
            list(SORT _f)
        endif ()
        string(APPEND _crate_key "${crate}@${_ndf}:${_f};")
    endforeach ()
    string(MD5 _crate_hash "${_crate_key}")
    string(SUBSTRING "${_crate_hash}" 0 12 _crate_hash_short)

    set(umbrella_name "nes_umbrella_${_crate_hash_short}")
    set(umbrella_dir "${CMAKE_BINARY_DIR}/rust-umbrellas/${_crate_hash_short}")

    # If an umbrella for this exact crate+features set already exists, just link it.
    if (TARGET ${umbrella_name})
        _link_umbrella_with_bridges(${exe_target} ${umbrella_name} "${_crates}")
        return()
    endif ()

    set(dep_lines "")
    set(extern_lines "")
    foreach (crate IN LISTS _crates)
        get_property(crate_path GLOBAL PROPERTY NES_RUST_CRATE_${crate}_PATH)
        if (NOT crate_path)
            message(FATAL_ERROR
                    "Rust crate '${crate}' required by ${exe_target} was not registered "
                    "with register_rust_crate(). Add a register_rust_crate() call in EnableRust.cmake.")
        endif ()
        get_property(_f GLOBAL PROPERTY _NES_UMB_${exe_target}_${crate}_FEATS)
        get_property(_ndf GLOBAL PROPERTY _NES_UMB_${exe_target}_${crate}_NDF)
        set(_line "${crate} = { path = \"${crate_path}\"")
        if (_ndf)
            string(APPEND _line ", default-features = false")
        endif ()
        if (_f)
            list(SORT _f)
            string(JOIN "\", \"" _fj ${_f})
            string(APPEND _line ", features = [\"${_fj}\"]")
        endif ()
        string(APPEND _line " }\n")
        string(APPEND dep_lines "${_line}")
        string(APPEND extern_lines "extern crate ${crate};\n")
    endforeach ()

    # Pin the CXX version to match the cxxbridge CLI that generated the C++ bridge code.
    # All workspaces MUST use the same CXX version (enforced by Cargo.lock alignment).
    file(WRITE "${umbrella_dir}/Cargo.toml"
            "[package]
name = \"${umbrella_name}\"
version = \"0.1.0\"
edition = \"2024\"

[lib]
crate-type = [\"staticlib\"]

# Opt out of root workspace — umbrella crates are standalone.
[workspace]

[dependencies]
cxx = \"=${NES_CXX_VERSION}\"
linkme = \"=0.3.35\"
${dep_lines}")

    file(WRITE "${umbrella_dir}/.cargo/config.toml"
            "[build]
rustflags = []
")


    file(MAKE_DIRECTORY "${umbrella_dir}/src")
    file(WRITE "${umbrella_dir}/src/lib.rs" "${extern_lines}")

    set(import_args
            MANIFEST_PATH "${umbrella_dir}/Cargo.toml"
            CRATES ${umbrella_name}
            CRATE_TYPES staticlib
    )
    if (NOT "${NES_RUST_CARGO_FLAGS}" STREQUAL "")
        list(APPEND import_args FLAGS ${NES_RUST_CARGO_FLAGS})
    endif ()
    corrosion_import_crate(${import_args})

    if (NOT "${NES_RUST_ENV_VARS}" STREQUAL "")
        set_property(TARGET ${umbrella_name}
                PROPERTY CORROSION_ENVIRONMENT_VARIABLES ${NES_RUST_ENV_VARS})
    endif ()

    _link_umbrella_with_bridges(${exe_target} ${umbrella_name} "${_crates}")
endfunction()

# Link the umbrella in a sandwich: umbrella → bridges → umbrella.
# With the header/symbol split, C++ consumers only link -headers targets,
# so bridges appear exclusively through the umbrella's INTERFACE_LINK_LIBRARIES.
# The sandwich resolves both FFI directions:
#   Pass 1 (umbrella): Rust symbols for earlier C++ callers
#   Pass 2 (bridges):  C++ symbols for Rust extern "C++" calls
#   Pass 3 (umbrella): Rust symbols needed by bridge code from pass 2
function(_link_umbrella_with_bridges exe_target umbrella_name rust_libs)
    get_target_property(_configured ${umbrella_name} _NES_BRIDGE_CONFIGURED)
    if (NOT _configured)
        set(_umbrella_file "$<TARGET_FILE:${umbrella_name}-static>")
        foreach (crate ${rust_libs})
            get_property(_bridge GLOBAL PROPERTY NES_CXX_BRIDGE_${crate})
            if (_bridge)
                set_property(TARGET ${umbrella_name} APPEND PROPERTY
                        INTERFACE_LINK_LIBRARIES ${_bridge})
            endif ()
        endforeach ()
        # Second umbrella copy (file path to avoid dedup) resolves Rust symbols
        # needed by bridge objects extracted in the previous step.
        set_property(TARGET ${umbrella_name} APPEND PROPERTY
                INTERFACE_LINK_LIBRARIES "$<LINK_LIBRARY:WHOLE_ARCHIVE,${_umbrella_file}>")
        set_target_properties(${umbrella_name} PROPERTIES _NES_BRIDGE_CONFIGURED TRUE)
    endif ()

    set_property(TARGET ${exe_target} APPEND PROPERTY LINK_LIBRARIES ${umbrella_name})
endfunction()
