/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#pragma once

#include <cstddef>
#include <cstdint>
#include <memory>
#include <optional>
#include <string>
#include <vector>
#include <Functions/NodeFunctionFieldAccess.hpp>
#include <Functions/NodeFunctionFieldAssignment.hpp>
#include <Operators/LogicalOperators/Windows/Aggregations/WindowAggregationDescriptor.hpp>
#include <Operators/LogicalOperators/Windows/Joins/LogicalJoinDescriptor.hpp>
#include <Plans/Query/QueryPlan.hpp>
#include <Sinks/SinkDescriptor.hpp>

namespace NES::Parsers
{


/// This class represents the results from parsing the ANTLR AST tree
/// Attributes of this class represent the different clauses and a merge into a query after parsing the AST
enum class AntlrSQLWindowType : uint8_t
{
    NO_WINDOW,
    WINDOW_SLIDING,
    WINDOW_TUMBLING,
    WINDOW_THRESHOLD,
};

class AntlrSQLHelper
{
    std::vector<std::shared_ptr<NodeFunction>> projectionFields; ///vector needed for logicalProjectionOperator constructor
    std::vector<std::shared_ptr<NodeFunction>> whereClauses; ///where and having clauses need to be accessed in reverse
    std::vector<std::shared_ptr<NodeFunction>> havingClauses;
    std::string source;

public:
    /// Constructors
    AntlrSQLHelper() = default;

    /// Query plans generated by antlr sql query parser.
    std::vector<std::shared_ptr<QueryPlan>> queryPlans;

    /// Flags used to determine which token we are currently parsing.
    bool isSelect = false;
    bool isWhereOrHaving = false;
    bool isFrom = false;
    bool isWindow = false;
    bool isArithmeticBinary = false;
    bool isJoinRelation = false;
    bool isSimpleCondition = true;
    bool isTimeBasedWindow = true;
    bool isSetOperation = false;
    bool isGroupBy = false;
    bool hasMultipleAttributes = false;

    bool isInFunctionCall() const { return not functionBuilder.empty(); }

    bool isInAggFunction() const { return not windowAggs.empty(); }

    /// Containers that hold state of specific objects that we create during parsing.
    std::shared_ptr<Windowing::WindowType> windowType;
    std::vector<std::shared_ptr<Windowing::WindowAggregationDescriptor>> windowAggs;
    std::vector<std::shared_ptr<Sinks::SinkDescriptor>> sinkDescriptor;
    std::vector<std::string> constantBuilder;
    std::vector<std::shared_ptr<NodeFunction>> functionBuilder;
    std::vector<std::shared_ptr<NodeFunctionFieldAssignment>> mapBuilder;
    std::vector<std::shared_ptr<NodeFunctionFieldAccess>> groupByFields;
    std::vector<std::string> joinSources;
    std::shared_ptr<NodeFunction> joinFunction;
    std::vector<std::shared_ptr<NodeFunction>> joinKeyRelationHelper;
    std::vector<std::string> joinSourceRenames;
    Join::LogicalJoinDescriptor::JoinType joinType;

    /// Utility variables to keep state between enter/exit parser function calls.
    size_t opBoolean; ///anonymous token enum in AntlrSQLLexer.h
    std::string opValue;
    std::string newSourceName;
    std::string timestamp;

    /// Utility variables used to keep track of the parsing state.
    int size;
    int advanceBy;
    size_t timeUnit; ///anonymous token enum in AntlrSQLLexer.h
    size_t timeUnitAdvanceBy;
    std::optional<int> minimumCount;
    int implicitMapCountHelper = 0;

    [[nodiscard]] const std::vector<std::shared_ptr<NodeFunction>>& getWhereClauses() const;
    [[nodiscard]] const std::vector<std::shared_ptr<NodeFunction>>& getHavingClauses() const;
    [[nodiscard]] const std::vector<std::shared_ptr<NodeFunction>>& getProjectionFields() const;
    void addWhereClause(const std::shared_ptr<NodeFunction>& expressionNode);
    void addHavingClause(const std::shared_ptr<NodeFunction>& expressionNode);
    void addProjectionField(const std::shared_ptr<NodeFunctionFieldAccess>& expressionNode);
    [[nodiscard]] static std::shared_ptr<Windowing::WindowType> getWindowType();
    void setSource(std::string sourceName);
    const std::string getSource() const;
    void addMapExpression(std::shared_ptr<NodeFunctionFieldAssignment> expressionNode);
    [[nodiscard]] std::vector<std::shared_ptr<NodeFunctionFieldAssignment>> getMapExpressions() const;
    void setMapExpressions(std::vector<std::shared_ptr<NodeFunctionFieldAssignment>> expressions);
};
}
