/*
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#pragma once

#include <cstddef>
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <Functions/FieldAccessLogicalFunction.hpp>
#include <Functions/FieldAssignmentLogicalFunction.hpp>
#include <Operators/Windows/Aggregations/WindowAggregationFunction.hpp>
#include <Operators/Windows/JoinLogicalOperator.hpp>
#include <Plans/QueryPlan.hpp>
#include <Sinks/SinkDescriptor.hpp>

namespace NES::Parsers
{

class AntlrSQLHelper
{
    std::vector<std::unique_ptr<LogicalFunction>> projectionFields;
    std::vector<std::unique_ptr<LogicalFunction>> whereClauses;
    std::vector<std::unique_ptr<LogicalFunction>> havingClauses;
    std::string source;

public:
    /// Constructors
    AntlrSQLHelper() = default;

    /// Explicitly deleted copy.
    AntlrSQLHelper(const AntlrSQLHelper&) = delete;
    AntlrSQLHelper& operator=(const AntlrSQLHelper&) = delete;

    /// Default move operations.
    AntlrSQLHelper(AntlrSQLHelper&&) noexcept = default;
    AntlrSQLHelper& operator=(AntlrSQLHelper&&) noexcept = default;

    /// Query plans generated by antlr sql query parser.
    std::vector<QueryPlan> queryPlans;

    /// Flags used to determine which token we are currently parsing.
    bool isSelect = false;
    bool isWhereOrHaving = false;
    bool isFrom = false;
    bool isWindow = false;
    bool isArithmeticBinary = false;
    bool isJoinRelation = false;
    bool isFunctionCall = false;
    bool isSimpleCondition = true;
    bool isTimeBasedWindow = true;
    bool isSetOperation = false;
    bool isGroupBy = false;
    bool hasMultipleAttributes = false;

    /// Containers that hold state of specific objects that we create during parsing.
    std::unique_ptr<Windowing::WindowType> windowType;
    std::vector<std::unique_ptr<WindowAggregationFunction>> windowAggs;
    std::vector<std::unique_ptr<LogicalFunction>> projections;
    std::vector<std::unique_ptr<Sinks::SinkDescriptor>> sinkDescriptor;
    std::vector<std::unique_ptr<LogicalFunction>> functionBuilder;
    std::vector<std::unique_ptr<FieldAssignmentLogicalFunction>> mapBuilder;
    std::vector<std::unique_ptr<FieldAccessLogicalFunction>> groupByFields;
    std::vector<std::string> joinSources;
    std::unique_ptr<LogicalFunction> joinFunction;
    std::vector<std::unique_ptr<LogicalFunction>> joinKeyRelationHelper;
    std::vector<std::string> joinSourceRenames;
    Join::LogicalJoinDescriptor::JoinType joinType;

    /// Utility variables to keep state between enter/exit parser function calls.
    size_t opBoolean; ///anonymous token enum in AntlrSQLLexer.h
    std::string opValue;
    std::string newSourceName;
    std::string timestamp;

    /// Utility variables used to keep track of the parsing state.
    int size;
    int advanceBy;
    size_t timeUnit; ///anonymous token enum in AntlrSQLLexer.h
    size_t timeUnitAdvanceBy;
    std::optional<int> minimumCount;
    int identCountHelper = 0;
    int implicitMapCountHelper = 0;

    [[nodiscard]] std::vector<std::unique_ptr<LogicalFunction>>& getWhereClauses();
    [[nodiscard]] std::vector<std::unique_ptr<LogicalFunction>>& getHavingClauses();
    [[nodiscard]] std::vector<std::unique_ptr<LogicalFunction>>& getProjectionFields();
    void addWhereClause(std::unique_ptr<LogicalFunction> expressionNode);
    void addHavingClause(std::unique_ptr<LogicalFunction> expressionNode);
    void addProjectionField(std::unique_ptr<LogicalFunction> expressionNode);
    [[nodiscard]] const std::unique_ptr<Windowing::WindowType> getWindowType() const;
    void setSource(std::string sourceName);
    [[nodiscard]] const std::string getSource() const;
    void addMapExpression(std::unique_ptr<FieldAssignmentLogicalFunction> expressionNode);
    [[nodiscard]] std::vector<std::unique_ptr<FieldAssignmentLogicalFunction>> getMapExpressions() const;
    void setMapExpressions(std::vector<std::unique_ptr<FieldAssignmentLogicalFunction>> expressions);
};
}
