name: No closed Issue ID in TODOs
on:
  issues:
    types: [closed]

jobs:
  check-issue-TODOs-removed:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Check that no TODO with closed Issue remains
        run: |
          TODO_LINES=$(mktemp)
          if ! git grep -n -E -e "(///|#).* TODO #${{ github.event.issue.number }}([^0-9]|$)" > $TODO_LINES  # NO_TODO_CHECK
          then
            echo "found no TODOs referencing #${{ github.event.issue.number }}" >> $GITHUB_STEP_SUMMARY
            exit 0
          fi

          # re-open issue
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
            -d '{"state":"open"}'

          cat > issue_msg.json << EOF
          FYI @${{ github.event.sender.login }}, this issue was automatically reopened since the following TODO comments still reference it:

          \`\`\`
          $(cat $TODO_LINES)
          \`\`\`

          EOF

          cat issue_msg.json >> $GITHUB_STEP_SUMMARY

          echo "See also run [${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> issue_msg.json

          # Add comment referencing user that closed the issue
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -d "{\"body\":\"$(cat issue_msg.json | sed -z "s/\n/\\\n/g")\"}"

          exit 1
