name: Calculating Development Metrics

# The following pipeline is meant to be run per milestone by a workflow dispatch call via the Github website.
# It will calculate the development metrics for the milestone.
# For example, the number of PRs, the number of commits, the number of issues, PR turnaround time, etc.

on:
  workflow_dispatch:
    inputs:
      fromdate:
        description: 'Interval start date (format: yyyy-mm-dd)'
        required: true
      todate:
        description: 'Interval end date (format: yyyy-mm-dd)'
        required: true

jobs:
  repo-metrics-report:
    runs-on: [ self-hosted, linux, Build, x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get dates for period
        shell: bash
        run: |
          echo "period=${{ github.event.inputs.fromdate }}..${{ github.event.inputs.todate }}" >> "$GITHUB_ENV"

      - name: Get metrics for Issues
        uses: github/issue-metrics@v3
        env:
          SEARCH_QUERY: 'repo:nebulastream/nebulastream-public is:issue created:${{ env.period }} -reason:"not planned"'

      - name: Rename the output file
        run: mv issue_metrics.md metrics_for_issues.md

      - name: Get metrics for PRs
        uses: github/issue-metrics@v3
        env:
          SEARCH_QUERY: 'repo:nebulastream/nebulastream-public is:pr created:${{ env.period }} -reason:"not planned"'
          REPORT_TITLE: 'Metrics for PRs'

      - name: Rename the output file
        run: mv issue_metrics.md metrics_for_prs.md

      - name: Create folder and move files
        run: |
          mkdir -p ./metrics
          mv metrics_for_issues.md ./metrics
          mv metrics_for_prs.md ./metrics

      - name: Publish Markdown files to Github Summary
        run: |
          metrics_for_issues=$(cat ./metrics/metrics_for_issues.md)
          metrics_for_prs=$(cat ./metrics/metrics_for_prs.md)
          echo "$metrics_for_prs" >> $GITHUB_STEP_SUMMARY
          echo "\n\n" >> $GITHUB_STEP_SUMMARY
          echo "$metrics_for_issues" >> $GITHUB_STEP_SUMMARY

      - name: Upload Markdown to Artefacts
        uses: actions/upload-artifact@v4
        with:
          name: repo-metrics
          path: ./metrics
