name: Large Tests Random Worker Config
description: This workflow builds and tests a head_sha over our large tests with random worker configurations
on:
  workflow_call:
    inputs:
      dev_image_tag:
        required: true
        type: string
        description: "Docker image tag of the development image"
      head_sha:
        type: string
        required: true
        description: "head_sha of the branch"
jobs:
  run_large_scale_tests:
    name: Run Large Scale Tests Random Worker Config
    secrets: inherit
    uses: ./.github/workflows/large_test.yml
    with:
      head_sha: ${{ inputs.head_sha }}
      dev_image_tag: ${{ inputs.dev_image_tag }}
