name: NES Nightly
description: Validate PR 2012 with only the nightly UBSan configurations.

on:
  workflow_dispatch:
    inputs:
      head_sha:
        required: false
        description: "Commit to test (defaults to the dispatched branch)"

jobs:
  fetch-current-main-commit:
    runs-on: [ self-hosted ]
    outputs:
      sha: ${{ steps.fetch-sha.outputs.sha }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.head_sha || github.sha }}
      - name: Fetch SHA
        id: fetch-sha
        run: |
          git rev-parse --verify HEAD
          echo "sha=$(git rev-parse --verify HEAD)" >> "$GITHUB_OUTPUT"

  get-dev-images:
    needs: fetch-current-main-commit
    uses: ./.github/workflows/get_dev_images.yml
    secrets: inherit
    with:
      head_sha: ${{ needs.fetch-current-main-commit.outputs.sha }}

  build-and-test:
    name: "Run build and test"
    needs: [ fetch-current-main-commit, get-dev-images ]
    uses: ./.github/workflows/build_and_test.yml
    secrets: inherit
    with:
      head_sha: ${{ needs.fetch-current-main-commit.outputs.sha }}
      dev_image_tag: ${{ needs.get-dev-images.outputs.image-tag }}
      matrix_profile: nightly
