name: Build and profile benchmark systests
on:
  workflow_call:
    inputs:
      run_reason:
        required: true
        type: string
        description: "Reason why benchmark suite is being run"
      ref:
        type: string
        required: true
        description: "ref of the branch"
      dev_image_tag:
        required: true
        type: string
        description: "Docker image tag of the benchmarking image"

jobs:
  build-and-profile:
    runs-on: bc58-nes-public
    container:
      image: nebulastream/nes-benchmark:${{ inputs.dev_image_tag }}
      volumes:
        - ccache:/ccache
        - test-file-cache:/test-file-cache
      env:
        CCACHE_DIR: /ccache
        MOLD_JOBS: 1
        CONBENCH_PROJECT_COMMIT: ${{ inputs.ref }}
        CONBENCH_URL: "https://bench.nebula.stream"
        CONBENCH_EMAIL: ${{ secrets.CONBENCH_USR }}
        CONBENCH_PASSWORD: ${{ secrets.CONBENCH_PWD }}
        CONBENCH_PROJECT_REPOSITORY: "https://github.com/${{ github.repository }}"
        CONBENCH_RUN_REASON: ${{ inputs.run_reason }}
        CONBENCH_MACHINE_INFO_NAME: "Github Runner"
      options: --user root --privileged
    timeout-minutes: 60
    steps:
      - name: install flamegraphs tools
        run: |
          git clone https://github.com/brendangregg/Flamegraph.git
          echo "Flamegraphs tools cloned!"
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: build systest
        run: |
          cmake -GNinja -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_LARGE_TESTS=ON -DExternalData_OBJECT_STORES=/test-file-cache
          cmake --build build -j
      - name: profile benchmarks
        run: |
          SYSTEST_LIST=$(find ./nes-systests/benchmark -type f -name "*.test" | sed 's/.*\///' | sed 's/\.test$//' | sort)
          echo "Found the following tests: ${SYSTEST_LIST}"
          for SYSTEST_NAME in $SYSTEST_LIST; do
            TEST_PATH="./nes-systests/benchmark/${SYSTEST_NAME}.test"
            echo "Profiling ${TEST_PATH}"
            perf record -g ./build/nes-systests/systest/systest -t "$TEST_PATH"
            perf script > "${SYSTEST_NAME}.perf"
            ./Flamegraph/stackcollapse-perf.pl "${SYSTEST_NAME}.perf" > "${SYSTEST_NAME}.folded"
            grep -v 'systest' "./${SYSTEST_NAME}.folded" | grep -v 'StatPrinter' > "${SYSTEST_NAME}.filtered.folded"
            ./Flamegraph/flamegraph.pl --title=" " "${SYSTEST_NAME}.filtered.folded" > "${SYSTEST_NAME}.svg"
          done
      - name: upload svgs and metadata to conbench via curl
        run: |
          python3 ./scripts/benchmarking/benchmark.py --flamegraphs
