name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '37 17 * * *'

jobs:
  stale:
    if: ${{ !github.event.act }}
    runs-on: [ self-hosted, linux, x64, Build ]
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ github.token }}
        stale-issue-message: 'Stale issue message'
        stale-pr-message: 'Stale pull request message'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-close: -1
        days-before-pr-close: 14
        days-before-stale: 30
        operations-per-run: 500

