name: test-24h-stress
on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        required: true
        description: "ref of the branch"
        default: 1046-24h-nightly-runs
      dev_image_tag:
        type: string
        description: "nebulastream/nes-development tag"
        required: true
  pull_request:

jobs:
  get-dev-images:
    uses: ./.github/workflows/get_dev_images.yml
    secrets: inherit
    with:
      branch-name: ${{ github.head_ref }}
      ref: ${{ github.event.pull_request.head.sha }}

  call-stress:
    uses: ./.github/workflows/24h_stress_test.yml
    needs: [ get-dev-images ]
    with:
      ref: ${{ github.event.pull_request.head.ref }}
      dev_image_tag: ${{ needs.get-dev-images.outputs.image-tag }}