#ifndef NES_NES_EXECUTION_INCLUDE_INTERPRETER_TRACE_OPCODE_HPP_
#define NES_NES_EXECUTION_INCLUDE_INTERPRETER_TRACE_OPCODE_HPP_
namespace NES::Interpreter {
enum OpCode { ADD, SUB, DIV, MUL, EQUALS, LESS_THAN, NEGATE, AND, OR, CMP, JMP, CONST, ASSIGN, RETURN, LOAD, STORE, CALL };
}
#endif//NES_NES_EXECUTION_INCLUDE_INTERPRETER_TRACE_OPCODE_HPP_
